#!/usr/bin/env python3
"""Genera questions_part3.json — M9 + M12 (220 preguntas)"""
import json, os, sys
sys.path.insert(0,os.path.dirname(__file__))
from gen_questions_p1 import meta, TT, build

R=[
# ═══ M9 EMOCIONES (28) — Consolidacion de Habitos ═══
("Q-AMO-M9-EMO-001","C","Mantengo la regulación emocional incluso durante semanas de alta presión familiar o laboral."),
("Q-AMO-M9-EMO-002","A","Noto que mi familia ha comenzado a confiar en mi estabilidad emocional de forma natural."),
("Q-AMO-M9-EMO-003","F","He consolidado la práctica de reparar el vínculo después de cualquier error o conflicto."),
("Q-AMO-M9-EMO-004","M","En nuestra familia ya no existen recaídas y la transformación emocional es permanente.",True),
("Q-AMO-M9-EMO-005","E","Observo si hay emociones que siguen siendo difíciles de sostener sin apoyo externo."),
("Q-AMO-M9-EMO-006","C","Sostengo la compasión hacia los demás incluso cuando sus procesos son lentos o difíciles."),
("Q-AMO-M9-EMO-007","A","Noto que las recaídas emocionales son cada vez menos frecuentes e intensas."),
("Q-AMO-M9-EMO-008","F","Percibo que la estabilidad emocional familiar se ha consolidado como un nuevo estándar."),
("Q-AMO-M9-EMO-009","A","Me doy cuenta de que puedo acompañar las emociones difíciles de otros sin perder mi centro."),
("Q-AMO-M9-EMO-010","F","Acepto que consolidar la salud emocional familiar es un logro que requiere celebración."),
("Q-AMO-M9-EMO-011","C","Identifico que la familia ahora tiene recursos emocionales que antes no existían."),
("Q-AMO-M9-EMO-012","A","Noto si hay algún miembro que todavía experimenta crisis emocionales y necesita más apoyo."),
("Q-AMO-M9-EMO-013","F","Reconozco que la conciencia emocional ya es parte de nuestra identidad familiar colectiva."),
("Q-AMO-M9-EMO-014","M","Creo que ya hemos alcanzado el nivel máximo posible de salud emocional familiar.",True),
("Q-AMO-M9-EMO-015","E","Me pregunto qué nivel de conciencia emocional quiero que mi familia tenga en M12."),
("Q-AMO-M9-EMO-016","C","Logro sostener la alegría y la gratitud incluso cuando las circunstancias son adversas."),
("Q-AMO-M9-EMO-017","A","Noto que la capacidad de pedir y dar apoyo emocional en casa se ha normalizado."),
("Q-AMO-M9-EMO-018","F","Percibo que los conflictos ahora se resuelven con más rapidez y menos costo emocional."),
("Q-AMO-M9-EMO-019","A","Me doy cuenta de que la familia tiene ahora un nivel de tolerancia al malestar más alto."),
("Q-AMO-M9-EMO-020","F","Acepto que la consolidación emocional implica integrar tanto los logros como las recaídas."),
("Q-AMO-M9-EMO-021","C","Puedo sostener conversaciones emocionalmente cargadas sin perder la presencia ni la calma."),
("Q-AMO-M9-EMO-022","A","Noto que la vergüenza y el miedo son emociones que ya no dominan nuestras interacciones."),
("Q-AMO-M9-EMO-023","F","Identifico que la capacidad de celebrar los logros emocionales está instalada en nuestra familia."),
("Q-AMO-M9-EMO-024","A","Me doy cuenta de que la familia habla de sus emociones con mayor naturalidad y menos resistencia."),
("Q-AMO-M9-EMO-025","F","Reconozco que el proceso de nueve meses ha transformado nuestra forma de sentir y convivir."),
("Q-AMO-M9-EMO-026","C","Percibo que los hijos o jóvenes de la familia muestran mayor madurez emocional que antes."),
("Q-AMO-M9-EMO-027","A","Noto si persiste algún patrón emocional disfuncional que aún requiere trabajo consciente."),
("Q-AMO-M9-EMO-028","E","Me pregunto cómo se verá nuestra vida emocional cuando lleguemos a la etapa de Integridad Plena."),
# ═══ M9 COMUNICACION (28) ═══
("Q-AMO-M9-COM-001","C","Mantengo conversaciones profundas y honestas incluso cuando el tema es difícil o incómodo."),
("Q-AMO-M9-COM-002","A","Noto que la comunicación familiar fluye con más naturalidad y menos esfuerzo consciente."),
("Q-AMO-M9-COM-003","F","He consolidado el hábito de validar antes de responder en todas las conversaciones familiares."),
("Q-AMO-M9-COM-004","M","En nuestra familia la comunicación es ahora perfecta y no necesitamos seguir trabajándola.",True),
("Q-AMO-M9-COM-005","E","Observo si hay formas de comunicación que aún no hemos explorado y que podrían enriquecernos."),
("Q-AMO-M9-COM-006","C","Sostengo la escucha activa incluso cuando estoy cansado o bajo presión laboral."),
("Q-AMO-M9-COM-007","A","Noto que las palabras de aliento, reconocimiento y afecto son parte habitual de nuestro lenguaje."),
("Q-AMO-M9-COM-008","F","Percibo que la calidad de las conversaciones familiares refleja la consolidación del proceso."),
("Q-AMO-M9-COM-009","A","Me doy cuenta de que los malentendidos se resuelven ahora con más rapidez y menos drama."),
("Q-AMO-M9-COM-010","F","Acepto que la comunicación familiar consolidada es un patrimonio que debemos proteger."),
("Q-AMO-M9-COM-011","C","Identifico que la familia puede hablar de cualquier tema sin que los vínculos se dañen."),
("Q-AMO-M9-COM-012","A","Noto si hay temas que todavía se evitan y que podrían necesitar abordarse para avanzar."),
("Q-AMO-M9-COM-013","F","Reconozco que la comunicación honesta y amorosa ya forma parte de nuestra identidad familiar."),
("Q-AMO-M9-COM-014","M","Considero que todos los miembros de mi familia ya son comunicadores perfectos.",True),
("Q-AMO-M9-COM-015","E","Me pregunto qué tipo de comunicación queremos cultivar en la próxima etapa del proceso."),
("Q-AMO-M9-COM-016","C","Logro expresar mis límites con claridad y amor sin que genere conflicto en la familia."),
("Q-AMO-M9-COM-017","A","Noto que el lenguaje de responsabilidad ha reemplazado al lenguaje de culpa en mi familia."),
("Q-AMO-M9-COM-018","F","Percibo que los desacuerdos ahora son oportunidades de entendimiento y no de separación."),
("Q-AMO-M9-COM-019","A","Me doy cuenta de que los hijos o jóvenes de la familia se comunican con más asertividad."),
("Q-AMO-M9-COM-020","F","Acepto que la comunicación familiar en esta etapa es evidencia viva del trabajo de meses."),
("Q-AMO-M9-COM-021","C","Puedo recibir feedback difícil de los miembros de mi familia sin ponerme a la defensiva."),
("Q-AMO-M9-COM-022","A","Noto que ya no necesito elevar el tono ni callarme para sentirme escuchado en casa."),
("Q-AMO-M9-COM-023","F","Identifico que la calidez en la comunicación es ahora un rasgo distintivo de nuestra familia."),
("Q-AMO-M9-COM-024","A","Me doy cuenta de que hablar de sueños y proyectos familiares se ha vuelto más frecuente."),
("Q-AMO-M9-COM-025","F","Reconozco que la comunicación sostenida durante nueve meses ha cambiado nuestra cultura."),
("Q-AMO-M9-COM-026","C","Percibo que la familia tiene ahora conversaciones que construyen futuro en lugar de revivir pasado."),
("Q-AMO-M9-COM-027","A","Noto si hay alguien en la familia que aún tiene dificultades para comunicarse con apertura."),
("Q-AMO-M9-COM-028","E","Me pregunto cómo podríamos profundizar aún más la calidad de comunicación en M12."),
# ═══ M9 HABITOS (27) ═══
("Q-AMO-M9-HAB-001","C","Los hábitos de transformación están ahora tan consolidados que surgen de forma espontánea."),
("Q-AMO-M9-HAB-002","A","Noto que la familia ya no necesita recordatorios para practicar los hábitos acordados."),
("Q-AMO-M9-HAB-003","F","He consolidado hábitos de cuidado personal que me permiten estar mejor disponible para la familia."),
("Q-AMO-M9-HAB-004","M","Todos los hábitos que propusimos están integrados sin ningún esfuerzo ni resistencia.",True),
("Q-AMO-M9-HAB-005","E","Observo qué hábitos de la siguiente etapa podríamos comenzar a incorporar desde ahora."),
("Q-AMO-M9-HAB-006","C","Sostengo los hábitos de convivencia sana incluso durante épocas de estrés o cambio."),
("Q-AMO-M9-HAB-007","A","Noto que los hábitos de gratitud y reconocimiento mutuo son parte natural de nuestra vida."),
("Q-AMO-M9-HAB-008","F","Percibo que los hábitos de presencia consciente ya son un valor de nuestra familia."),
("Q-AMO-M9-HAB-009","A","Me doy cuenta de que algunos hábitos han evolucionado de forma orgánica con el proceso."),
("Q-AMO-M9-HAB-010","F","Acepto que mantener hábitos saludables en una familia requiere renovación y ajuste constante."),
("Q-AMO-M9-HAB-011","C","Identifico que los hábitos de nueve meses han transformado la identidad de nuestra familia."),
("Q-AMO-M9-HAB-012","A","Noto que los hijos han adoptado hábitos saludables que nosotros modelamos conscientemente."),
("Q-AMO-M9-HAB-013","F","Reconozco que los hábitos de conexión emocional ya son tan naturales como los físicos."),
("Q-AMO-M9-HAB-014","M","Considero que ya no necesitamos ningún tipo de refuerzo para mantener nuestros hábitos.",True),
("Q-AMO-M9-HAB-015","E","Me pregunto qué nuevos rituales familiares podríamos crear para celebrar nueve meses de proceso."),
("Q-AMO-M9-HAB-016","C","Logro mantener el hábito de la reparación emocional sin que requiera un esfuerzo enorme."),
("Q-AMO-M9-HAB-017","A","Noto si hay hábitos que empezaron bien pero se han debilitado con el tiempo y necesitan revisión."),
("Q-AMO-M9-HAB-018","F","Percibo que los hábitos de la familia reflejan los valores que queremos transmitir."),
("Q-AMO-M9-HAB-019","A","Me doy cuenta de que el hábito del diálogo familiar está completamente integrado en la rutina."),
("Q-AMO-M9-HAB-020","F","Acepto que los hábitos consolidados en esta etapa son el puente hacia el legado familiar."),
("Q-AMO-M9-HAB-021","C","Puedo identificar con claridad los hábitos que definen quiénes somos como familia hoy."),
("Q-AMO-M9-HAB-022","A","Noto que la familia tiene ahora una capacidad de adaptación de hábitos mayor que antes."),
("Q-AMO-M9-HAB-023","F","Identifico que la coherencia entre lo que decimos y hacemos en familia ha aumentado mucho."),
("Q-AMO-M9-HAB-024","A","Me doy cuenta de que los hábitos de celebración y festejo familiar fortalecen nuestra identidad."),
("Q-AMO-M9-HAB-025","E","Me pregunto cómo nuestros hábitos actuales están moldeando a las futuras generaciones."),
("Q-AMO-M9-HAB-026","C","Reconozco que en nueve meses hemos construido una base de hábitos que ya no se puede ignorar."),
("Q-AMO-M9-HAB-027","F","Percibo que los hábitos familiares consolidados son el fundamento más sólido para el legado.",False,True),
# ═══ M9 TIEMPOS (27) ═══
("Q-AMO-M9-TIE-001","C","El tiempo familiar es ahora una prioridad no negociable en nuestra vida cotidiana."),
("Q-AMO-M9-TIE-002","A","Noto que los ritmos de la familia están más sincronizados y generan menos conflicto."),
("Q-AMO-M9-TIE-003","F","He consolidado rituales de tiempo compartido que definen nuestra identidad como familia."),
("Q-AMO-M9-TIE-004","M","En nuestra familia todos gestionamos el tiempo perfectamente y nunca hay desbalances.",True),
("Q-AMO-M9-TIE-005","E","Observo cómo el uso del tiempo en familia ha evolucionado desde la etapa de inicio."),
("Q-AMO-M9-TIE-006","C","Sostengo el compromiso de presencia consciente incluso en semanas muy exigentes."),
("Q-AMO-M9-TIE-007","A","Noto que las comidas y rituales familiares son protegidos de interrupciones con más firmeza."),
("Q-AMO-M9-TIE-008","F","Percibo que la familia valora el tiempo compartido como uno de sus recursos más preciosos."),
("Q-AMO-M9-TIE-009","A","Me doy cuenta de que el equilibrio entre trabajo y familia es más sostenible que antes."),
("Q-AMO-M9-TIE-010","F","Acepto que la gestión del tiempo familiar en M9 es evidencia del crecimiento del proceso."),
("Q-AMO-M9-TIE-011","C","Identifico que los momentos sin pantallas son ahora normales y deseados por todos."),
("Q-AMO-M9-TIE-012","A","Noto que el tiempo invertido en la pareja fortalece la base de toda la familia."),
("Q-AMO-M9-TIE-013","F","Reconozco que los rituales de tiempo familiar crean la memoria emocional que une a la familia."),
("Q-AMO-M9-TIE-014","M","Considero que ya organizamos el tiempo familiar perfectamente sin ningún área de mejora.",True),
("Q-AMO-M9-TIE-015","E","Me pregunto qué experiencias de tiempo compartido quiero crear antes de llegar a M12."),
("Q-AMO-M9-TIE-016","C","Logro mantener el balance entre tiempo personal, de pareja, familiar y social de forma consciente."),
("Q-AMO-M9-TIE-017","A","Noto que el tiempo de descanso compartido es tan valioso como el tiempo de actividad."),
("Q-AMO-M9-TIE-018","F","Percibo que los nueve meses de proceso han cambiado radicalmente cómo usamos el tiempo."),
("Q-AMO-M9-TIE-019","A","Me doy cuenta de que los miembros más jóvenes valoran y disfrutan el tiempo familiar ahora."),
("Q-AMO-M9-TIE-020","F","Acepto que el tiempo de calidad que hemos cultivado es ya parte de nuestra cultura familiar."),
("Q-AMO-M9-TIE-021","C","Puedo decir con claridad cuánto tiempo dedico cada semana a cada dimensión de la familia."),
("Q-AMO-M9-TIE-022","A","Noto si hay algún miembro que siente que no recibe suficiente tiempo o atención de mi parte."),
("Q-AMO-M9-TIE-023","F","Identifico que los rituales de tiempo que creamos se han convertido en tradiciones de la familia."),
("Q-AMO-M9-TIE-024","A","Me doy cuenta de que la familia planifica actividades compartidas con más frecuencia e ilusión."),
("Q-AMO-M9-TIE-025","E","Me pregunto qué legado de tiempo y presencia estoy construyendo para quienes vienen después."),
("Q-AMO-M9-TIE-026","C","Reconozco que el tiempo familiar bien gestionado durante nueve meses ya tiene frutos visibles."),
("Q-AMO-M9-TIE-027","F","Percibo que el tiempo y la presencia son los regalos más transformadores que doy a mi familia.",False,True),
# ═══ M12 EMOCIONES (28) — Integridad Plena ═══
("Q-AMO-M12-EMO-001","C","He integrado la regulación emocional como parte permanente de quien soy dentro de mi familia."),
("Q-AMO-M12-EMO-002","A","Noto que un año de trabajo emocional ha cambiado fundamentalmente cómo me relaciono en casa."),
("Q-AMO-M12-EMO-003","F","La familia vive en un clima emocional de seguridad y confianza que antes era impensable."),
("Q-AMO-M12-EMO-004","M","Nuestra familia ha alcanzado la integridad emocional perfecta y ya no necesita evolucionar.",True),
("Q-AMO-M12-EMO-005","E","Observo qué aspectos emocionales deseo seguir profundizando en la etapa de Entrega que viene."),
("Q-AMO-M12-EMO-006","C","Sostengo la calma y la presencia emocional incluso cuando el mundo externo está en caos."),
("Q-AMO-M12-EMO-007","A","Noto que la familia en su conjunto ha desarrollado inteligencia emocional colectiva real."),
("Q-AMO-M12-EMO-008","F","Percibo que puedo nombrar y gestionar cualquier emoción que surja con conciencia plena."),
("Q-AMO-M12-EMO-009","A","Me doy cuenta de que un año de proceso ha sanado heridas que creí que nunca cerrarían."),
("Q-AMO-M12-EMO-010","F","Acepto que la integridad emocional plena no es perfección sino coherencia honesta y constante."),
("Q-AMO-M12-EMO-011","C","Identifico que la familia ahora se acompaña emocionalmente con profundidad y sin juicio."),
("Q-AMO-M12-EMO-012","A","Noto que la alegría, la paz y el amor son los estados emocionales dominantes en mi hogar."),
("Q-AMO-M12-EMO-013","F","Reconozco que un año de integridad emocional nos ha posicionado para trascender como familia."),
("Q-AMO-M12-EMO-014","M","Creo que como familia ya somos emocionalmente perfectos y no hay más por trabajar.",True),
("Q-AMO-M12-EMO-015","E","Me pregunto qué emociones nuevas debo cultivar para entrar en la etapa de Entrega."),
("Q-AMO-M12-EMO-016","C","Logro sostener el amor como estado emocional activo incluso en los momentos más difíciles."),
("Q-AMO-M12-EMO-017","A","Noto que la familia puede atravesar momentos de dolor sin perder la cohesión ni el amor."),
("Q-AMO-M12-EMO-018","F","Percibo que el trabajo emocional de doce meses nos ha convertido en una familia más fuerte."),
("Q-AMO-M12-EMO-019","A","Me doy cuenta de que el perdón ya no es un esfuerzo sino una práctica natural en nosotros."),
("Q-AMO-M12-EMO-020","F","Acepto que la integridad emocional plena es la base sobre la que se construirá el legado."),
("Q-AMO-M12-EMO-021","C","Puedo ver con claridad la diferencia entre quién era emocionalmente hace un año y quién soy hoy."),
("Q-AMO-M12-EMO-022","A","Noto que otros fuera de la familia perciben la transformación emocional que hemos logrado."),
("Q-AMO-M12-EMO-023","F","Identifico que la madurez emocional familiar alcanzada es ahora un recurso para ayudar a otros."),
("Q-AMO-M12-EMO-024","A","Me doy cuenta de que la familia puede hablar de la muerte, el duelo y el miedo sin derrumbarse."),
("Q-AMO-M12-EMO-025","F","Reconozco que doce meses de transformación emocional es un logro que merece plena celebración."),
("Q-AMO-M12-EMO-026","C","Percibo que nuestra familia es ahora un modelo de salud emocional para nuestro entorno."),
("Q-AMO-M12-EMO-027","A","Noto si hay alguna dimensión emocional que aún requiere trabajo antes de entrar a Entrega."),
("Q-AMO-M12-EMO-028","E","Me pregunto qué legado emocional quiero dejar a las próximas generaciones de mi familia."),
# ═══ M12 COMUNICACION (28) ═══
("Q-AMO-M12-COM-001","C","La comunicación en nuestra familia es ahora un reflejo auténtico de la integridad que vivimos."),
("Q-AMO-M12-COM-002","A","Noto que las conversaciones familiares tienen una profundidad que hace un año era imposible."),
("Q-AMO-M12-COM-003","F","He integrado la comunicación honesta, amorosa y valiente como un estilo de vida familiar."),
("Q-AMO-M12-COM-004","M","En nuestra familia la comunicación es perfectamente honesta y nunca genera conflicto.",True),
("Q-AMO-M12-COM-005","E","Observo qué nuevas formas de comunicación podríamos explorar en la etapa de Entrega."),
("Q-AMO-M12-COM-006","C","Sostengo conversaciones difíciles con serenidad, amor y sin necesidad de ganar o perder."),
("Q-AMO-M12-COM-007","A","Noto que un año de práctica comunicativa ha eliminado los patrones destructivos del pasado."),
("Q-AMO-M12-COM-008","F","Percibo que la familia puede comunicar vulnerabilidad, sueños y miedos sin vergüenza."),
("Q-AMO-M12-COM-009","A","Me doy cuenta de que la comunicación familiar es ahora nuestra mayor fortaleza colectiva."),
("Q-AMO-M12-COM-010","F","Acepto que la integridad comunicativa implica decir lo que se siente aunque sea incómodo."),
("Q-AMO-M12-COM-011","C","Identifico que el lenguaje familiar ha evolucionado hacia la construcción y no la destrucción."),
("Q-AMO-M12-COM-012","A","Noto que todos los miembros de la familia pueden expresar sus necesidades sin miedo."),
("Q-AMO-M12-COM-013","F","Reconozco que la calidad de la comunicación en M12 es evidencia de integridad real."),
("Q-AMO-M12-COM-014","M","Considero que nuestra familia ya no necesita seguir trabajando la comunicación.",True),
("Q-AMO-M12-COM-015","E","Me pregunto cómo la calidad de nuestra comunicación puede servir de modelo para otros."),
("Q-AMO-M12-COM-016","C","Logro comunicarme con cada miembro de mi familia desde la verdad y desde el amor pleno."),
("Q-AMO-M12-COM-017","A","Noto que los silencios en casa comunican paz y no evitación ni distancia emocional."),
("Q-AMO-M12-COM-018","F","Percibo que las palabras de amor, reconocimiento y gratitud son parte diaria del hogar."),
("Q-AMO-M12-COM-019","A","Me doy cuenta de que la familia usa el diálogo como herramienta de crecimiento permanente."),
("Q-AMO-M12-COM-020","F","Acepto que sostener la integridad comunicativa requiere vigilancia y voluntad constante."),
("Q-AMO-M12-COM-021","C","Puedo comunicar mis valores, mi visión y mi amor de manera coherente con mis acciones."),
("Q-AMO-M12-COM-022","A","Noto que las nuevas generaciones están aprendiendo a comunicarse desde nuestro ejemplo."),
("Q-AMO-M12-COM-023","F","Identifico que la comunicación íntegra de doce meses ha construido confianza profunda."),
("Q-AMO-M12-COM-024","A","Me doy cuenta de que la familia puede ahora comunicar críticas constructivas con amor."),
("Q-AMO-M12-COM-025","F","Reconozco que la comunicación familiar plena es el puente hacia la etapa de Entrega."),
("Q-AMO-M12-COM-026","C","Percibo que nuestra forma de comunicarnos inspira a quienes nos rodean fuera del hogar."),
("Q-AMO-M12-COM-027","A","Noto si hay patrones comunicativos del pasado que aún requieren trabajo antes de trascender."),
("Q-AMO-M12-COM-028","E","Me pregunto qué conversación transformadora quiero tener con mi familia al cerrar este año."),
# ═══ M12 HABITOS (27) ═══
("Q-AMO-M12-HAB-001","C","Los hábitos de transformación son ahora la expresión natural de quiénes somos como familia."),
("Q-AMO-M12-HAB-002","A","Noto que un año de hábitos conscientes ha reconfigurado la cultura de nuestro hogar."),
("Q-AMO-M12-HAB-003","F","He integrado hábitos de integridad plena que son coherentes con mis valores más profundos."),
("Q-AMO-M12-HAB-004","M","Nuestra familia tiene todos sus hábitos perfectamente integrados sin ninguna área débil.",True),
("Q-AMO-M12-HAB-005","E","Observo qué hábitos de la etapa de Entrega necesito comenzar a cultivar desde ahora."),
("Q-AMO-M12-HAB-006","C","Sostengo los hábitos de conexión emocional incluso cuando las circunstancias cambian."),
("Q-AMO-M12-HAB-007","A","Noto que los hábitos de salud emocional familiar ya no dependen de mi esfuerzo sino de mi ser."),
("Q-AMO-M12-HAB-008","F","Percibo que los hábitos cultivados en un año son ya el ADN de nuestra convivencia familiar."),
("Q-AMO-M12-HAB-009","A","Me doy cuenta de que los hábitos de la familia en M12 son los cimientos del legado generacional."),
("Q-AMO-M12-HAB-010","F","Acepto que la integridad plena en los hábitos es la antesala de la etapa de Entrega."),
("Q-AMO-M12-HAB-011","C","Identifico que los hábitos de doce meses han transformado no solo conductas sino identidad."),
("Q-AMO-M12-HAB-012","A","Noto que los hábitos que practicamos ya son transmitidos naturalmente a las nuevas generaciones."),
("Q-AMO-M12-HAB-013","F","Reconozco que los hábitos íntegros que vivimos son el mejor legado que puedo dejar a mis hijos."),
("Q-AMO-M12-HAB-014","M","Creo que ya no necesitamos revisar ni ajustar ningún hábito porque todos están perfectos.",True),
("Q-AMO-M12-HAB-015","E","Me pregunto qué hábitos de trascendencia y generosidad podemos añadir en la siguiente etapa."),
("Q-AMO-M12-HAB-016","C","Logro sostener los hábitos de integridad incluso cuando nadie me observa ni valida."),
("Q-AMO-M12-HAB-017","A","Noto que los hábitos de apertura, gratitud y presencia ya son reflejos automáticos en mí."),
("Q-AMO-M12-HAB-018","F","Percibo que la familia en M12 vive sus hábitos desde la convicción y no desde la obligación."),
("Q-AMO-M12-HAB-019","A","Me doy cuenta de que doce meses de hábitos conscientes han transformado la salud de la familia."),
("Q-AMO-M12-HAB-020","F","Acepto que los hábitos que hemos construido merecen ser celebrados y transmitidos."),
("Q-AMO-M12-HAB-021","C","Puedo afirmar con honestidad cuáles hábitos ya están consolidados y cuáles siguen en proceso."),
("Q-AMO-M12-HAB-022","A","Noto que la familia diseña nuevos rituales con creatividad y sentido de propósito familiar."),
("Q-AMO-M12-HAB-023","F","Identifico que los hábitos de integridad plena son el puente hacia el crecimiento generacional."),
("Q-AMO-M12-HAB-024","A","Me doy cuenta de que los hábitos saludables ya no son un esfuerzo sino una elección gozosa."),
("Q-AMO-M12-HAB-025","E","Me pregunto cómo los hábitos que cultivamos hoy están construyendo el futuro de mi familia."),
("Q-AMO-M12-HAB-026","C","Reconozco que doce meses de hábitos conscientes nos han convertido en quienes deseábamos ser."),
("Q-AMO-M12-HAB-027","F","Percibo que la integridad en los hábitos familiares ya es una fuente de inspiración para otros.",False,True),
# ═══ M12 TIEMPOS (27) ═══
("Q-AMO-M12-TIE-001","C","El tiempo familiar se gestiona ahora con integridad plena y total coherencia con los valores."),
("Q-AMO-M12-TIE-002","A","Noto que en doce meses hemos transformado radicalmente cómo vivimos el tiempo en familia."),
("Q-AMO-M12-TIE-003","F","He integrado el tiempo consciente con la familia como un valor inamovible de mi vida."),
("Q-AMO-M12-TIE-004","M","En nuestra familia todos gestionamos el tiempo con integridad perfecta y sin fricciones.",True),
("Q-AMO-M12-TIE-005","E","Observo cómo el uso del tiempo familiar evolucionará en la etapa de Entrega y Legado."),
("Q-AMO-M12-TIE-006","C","Sostengo la presencia plena durante el tiempo familiar aunque el mundo externo exija atención."),
("Q-AMO-M12-TIE-007","A","Noto que los rituales de tiempo familiar de doce meses son ya tradiciones inamovibles."),
("Q-AMO-M12-TIE-008","F","Percibo que la calidad del tiempo compartido en M12 define la identidad familiar que somos."),
("Q-AMO-M12-TIE-009","A","Me doy cuenta de que el tiempo que invierto en la familia ya no genera culpa sino gozo."),
("Q-AMO-M12-TIE-010","F","Acepto que la integridad en el tiempo familiar implica mantener las promesas hechas a los míos."),
("Q-AMO-M12-TIE-011","C","Identifico que los ritmos familiares construidos en un año reflejan quiénes somos de verdad."),
("Q-AMO-M12-TIE-012","A","Noto que toda la familia puede articular cuáles son los momentos más sagrados de su semana."),
("Q-AMO-M12-TIE-013","F","Reconozco que doce meses de tiempo intencional han sembrado una memoria emocional duradera."),
("Q-AMO-M12-TIE-014","M","Considero que el manejo del tiempo en nuestra familia ya es perfecto y no necesita ajuste.",True),
("Q-AMO-M12-TIE-015","E","Me pregunto qué legado de presencia y tiempo quiero dejar a las generaciones que vienen."),
("Q-AMO-M12-TIE-016","C","Logro estar completamente presente en el tiempo familiar sin que mi mente divague al trabajo."),
("Q-AMO-M12-TIE-017","A","Noto que los momentos más simples compartidos en familia son ahora los más valorados por todos."),
("Q-AMO-M12-TIE-018","F","Percibo que el tiempo familiar de calidad que hemos cultivado es ya parte de nuestro legado."),
("Q-AMO-M12-TIE-019","A","Me doy cuenta de que la familia ahora protege activamente su tiempo compartido ante cualquier amenaza."),
("Q-AMO-M12-TIE-020","F","Acepto que el tiempo invertido en doce meses de transformación tiene un retorno incalculable."),
("Q-AMO-M12-TIE-021","C","Puedo mirar atrás doce meses y ver con claridad el impacto de cada momento de presencia."),
("Q-AMO-M12-TIE-022","A","Noto que la familia tiene ahora una historia compartida rica y significativa de un año."),
("Q-AMO-M12-TIE-023","F","Identifico que la integridad en el tiempo familiar en M12 es la base del legado generacional."),
("Q-AMO-M12-TIE-024","A","Me doy cuenta de que el tiempo familiar bien vivido es la herencia más valiosa que puedo dar."),
("Q-AMO-M12-TIE-025","E","Me pregunto qué nuevas formas de invertir el tiempo familiar necesito explorar en Entrega."),
("Q-AMO-M12-TIE-026","C","Reconozco que doce meses de tiempo intencional han construido una familia que trascenderá."),
("Q-AMO-M12-TIE-027","F","Percibo que el tiempo íntegro vivido en familia es ya la expresión más pura del amor en acción.",False,True),
]

out_path=os.path.join(os.path.dirname(__file__),"questions_part3.json")
data={"version":"2.0-part3","count":len(R),"questions":build(R)}
with open(out_path,"w",encoding="utf-8") as f:
    json.dump(data,f,ensure_ascii=False,indent=2)
print(f"OK Generadas {len(R)} preguntas -> {out_path}")
