#!/usr/bin/env python3
"""Genera questions-bank-v2.json — Parte 1: W1 + M1 (230 preguntas)"""
import json, os

def meta(qid):
    p=qid.split("-")
    pil={"REC":"reconocimiento","AMO":"amor","ENT":"entrega"}[p[1]]
    mil=p[2]; dim_c=p[3]
    dim={"EMO":"emociones","COM":"comunicacion","HAB":"habitos","TIE":"tiempos"}[dim_c]
    ph={"W1":"inconsciente","M1":"inconsciente","M3":"reactivo","M6":"reactivo","M9":"consciente","M12":"consciente","M18":"consciente","M24":"consciente","M30":"pleno","M36":"pleno"}[mil]
    sw={"W1":1.0,"M1":1.2,"M3":1.5,"M6":1.8,"M9":2.0,"M12":2.3,"M18":2.5,"M24":2.8,"M30":3.0,"M36":3.3}[mil]
    mg={"W1":"ESTABILIZACION_EMOCIONAL","M1":"RECONOCIMIENTO_VINCULAR","M3":"CIMENTACION_VINCULOS","M6":"TRANSFORMACION_PROFUNDA","M9":"CONSOLIDACION_HABITOS","M12":"INTEGRIDAD_PLENA","M18":"CRECIMIENTO_GENERACIONAL","M24":"LEGADO_FAMILIAR","M30":"TRASCENDENCIA","M36":"PLENITUD_TOTAL"}[mil]
    rt={"EMO":"desconexion_emocional","COM":"comunicacion_toxica","HAB":"falta_acuerdos","TIE":"ausencia_temporal"}[dim_c]
    cat={"EMO":"autoconciencia_emocional","COM":"escucha_activa","HAB":"rutinas_familiares","TIE":"presencia_consciente"}[dim_c]
    return pil,mil,dim,ph,sw,mg,rt,cat

TT={"C":"CORE","A":"ADAPTIVE","F":"FASE_PILLAR","M":"MIRROR","E":"EXPLORATORY"}

# (id, type_code, text [, rev=False [, rel=False]])
R=[
# ═══ W1 EMOCIONES ═══
("Q-REC-W1-EMO-001","C","Reconozco cuando estoy emocionalmente agotado antes de reaccionar con mi familia."),
("Q-REC-W1-EMO-002","A","Noto que mis emociones cambian drásticamente al llegar a casa después de un día difícil."),
("Q-REC-W1-EMO-003","F","Acepto que algunas heridas personales no resueltas están afectando nuestra convivencia."),
("Q-REC-W1-EMO-004","M","Creo que controlo perfectamente mis emociones sin afectar el clima del hogar.",True),
("Q-REC-W1-EMO-005","E","Me pregunto de dónde vienen mis reacciones más intensas hacia mi familia."),
("Q-REC-W1-EMO-006","C","Identifico la sensación física en mi cuerpo cuando estoy a punto de perder la calma."),
("Q-REC-W1-EMO-007","A","Noto que mi irritabilidad aumenta con la sobrecarga laboral o la falta de sueño."),
("Q-REC-W1-EMO-008","F","Percibo la tensión emocional en el hogar antes de que se convierta en conflicto abierto."),
("Q-REC-W1-EMO-009","M","En nuestra familia todos manejamos las emociones sin que afecten la convivencia.",True),
("Q-REC-W1-EMO-010","E","Observo cuáles son los momentos del día con mayor tensión emocional en casa."),
("Q-REC-W1-EMO-011","C","Puedo distinguir entre estar cansado físicamente y estar saturado emocionalmente."),
("Q-REC-W1-EMO-012","A","Noto si la rabia que expreso en casa proviene de algo ocurrido fuera del hogar."),
("Q-REC-W1-EMO-013","F","Reconozco que algunos comportamientos emocionales míos los aprendí en mi familia de origen."),
("Q-REC-W1-EMO-014","M","Pienso que las emociones negativas en casa son siempre responsabilidad de los demás.",True),
("Q-REC-W1-EMO-015","E","Identifico si hay emociones no expresadas que crean distancia en mi familia."),
("Q-REC-W1-EMO-016","C","Reconozco el momento en que las emociones de un miembro afectan a toda la familia."),
("Q-REC-W1-EMO-017","A","Noto si busco escapar emocionalmente cuando la convivencia se siente muy pesada."),
("Q-REC-W1-EMO-018","F","Acepto que el clima emocional de nuestra casa necesita atención y trabajo consciente."),
("Q-REC-W1-EMO-019","A","Noto si uso el silencio como castigo o como distancia emocional hacia mi familia."),
("Q-REC-W1-EMO-020","F","Percibo la diferencia entre lo que siento realmente y lo que comunico con mis reacciones."),
("Q-REC-W1-EMO-021","C","Reconozco cuando alguien en casa necesita apoyo emocional aunque no lo pida directamente."),
("Q-REC-W1-EMO-022","A","Noto que ciertos temas activan en mí una reactividad emocional automática e inmediata."),
("Q-REC-W1-EMO-023","F","Identifico las situaciones cotidianas que me generan más ansiedad o tensión en el hogar."),
("Q-REC-W1-EMO-024","A","Me doy cuenta de que proyecto emociones del trabajo en las interacciones familiares."),
("Q-REC-W1-EMO-025","F","Observo cómo mi estado emocional al despertar define el tono de la jornada familiar."),
("Q-REC-W1-EMO-026","C","Acepto que mi humor afecta directamente el bienestar emocional de toda la familia."),
("Q-REC-W1-EMO-027","A","Noto si respondo emocionalmente desde el miedo o desde la frustración acumulada."),
("Q-REC-W1-EMO-028","F","Reconozco que existen patrones emocionales repetitivos en la dinámica de nuestra familia."),
("Q-REC-W1-EMO-029","M","Considero que en nuestra familia nunca existen problemas emocionales significativos.",True),
("Q-REC-W1-EMO-030","E","Me pregunto qué emociones generacionales se heredan en nuestra dinámica familiar."),
# ═══ W1 COMUNICACION ═══
("Q-REC-W1-COM-001","C","Escucho completamente a mi familia antes de preparar mi respuesta."),
("Q-REC-W1-COM-002","A","Noto que interrumpo a los demás cuando dicen algo que me incomoda o contradice."),
("Q-REC-W1-COM-003","F","Acepto que mi comunicación en casa a veces hiere aunque no sea mi intención."),
("Q-REC-W1-COM-004","M","Soy siempre claro y empático en mis comunicaciones familiares sin excepción.",True),
("Q-REC-W1-COM-005","E","Observo qué temas evitamos hablar en familia por miedo o incomodidad."),
("Q-REC-W1-COM-006","C","Puedo hablar de lo que siento sin atacar ni ponerme a la defensiva."),
("Q-REC-W1-COM-007","A","Me doy cuenta de que uso palabras absolutas como 'siempre' o 'nunca' al reclamar."),
("Q-REC-W1-COM-008","F","Reconozco cuando mi tono cambia bruscamente si no me entienden a la primera."),
("Q-REC-W1-COM-009","M","Nunca uso palabras hirientes ni reproches del pasado en las discusiones familiares.",True),
("Q-REC-W1-COM-010","E","Me pregunto si mis gestos y lenguaje corporal contradicen lo que digo con palabras."),
("Q-REC-W1-COM-011","C","Identifico cuando estoy presente físicamente pero ausente mentalmente en conversaciones."),
("Q-REC-W1-COM-012","A","Noto si busco tener la última palabra en los desacuerdos familiares cotidianos."),
("Q-REC-W1-COM-013","F","Acepto que a veces asumo lo que los demás piensan sin preguntarles directamente."),
("Q-REC-W1-COM-014","M","En nuestra familia siempre nos escuchamos con plena atención y sin interrupciones.",True),
("Q-REC-W1-COM-015","E","Observo si hay un patrón comunicativo que siempre termina en distancia o silencio."),
("Q-REC-W1-COM-016","C","Reconozco la diferencia entre escuchar para comprender y escuchar para responder."),
("Q-REC-W1-COM-017","A","Me doy cuenta de que evito conversaciones difíciles cuando estoy cansado o sobrecargado."),
("Q-REC-W1-COM-018","F","Percibo si mi comunicación busca imponer mi voluntad o generar acuerdos reales."),
("Q-REC-W1-COM-019","A","Noto si oculto mis sentimientos verdaderos para evitar conflictos en el hogar."),
("Q-REC-W1-COM-020","F","Identifico cuándo mi comunicación nace del miedo y no de la honestidad afectiva."),
("Q-REC-W1-COM-021","C","Puedo notar cuando hablo más de los demás que de mis propios procesos internos."),
("Q-REC-W1-COM-022","A","Noto si delego la responsabilidad de la mala comunicación siempre en el otro."),
("Q-REC-W1-COM-023","F","Reconozco que las conversaciones difíciles son necesarias para el crecimiento familiar."),
("Q-REC-W1-COM-024","A","Me doy cuenta de que respondo de forma cortante cuando estoy abrumado por el trabajo."),
("Q-REC-W1-COM-025","F","Acepto que mejorar mi comunicación familiar requiere práctica consciente y voluntad."),
("Q-REC-W1-COM-026","C","Identifico si al pedir ayuda en casa lo hago con exigencia o con invitación amorosa."),
("Q-REC-W1-COM-027","A","Noto si solo aparezco en conversaciones para dar órdenes o instrucciones."),
("Q-REC-W1-COM-028","F","Percibo la diferencia entre una conversación que une y una que crea más distancia."),
("Q-REC-W1-COM-029","E","Me pregunto cuántos acuerdos familiares existen y cuántos se cumplen realmente."),
("Q-REC-W1-COM-030","E","Observo qué conversaciones del día construyeron conexión y cuáles generaron separación."),
# ═══ W1 HABITOS ═══
("Q-REC-W1-HAB-001","C","Cumplo los acuerdos familiares aunque no tenga ganas en ese momento."),
("Q-REC-W1-HAB-002","A","Noto que el hábito de mirar el celular es mi primera reacción al llegar a casa."),
("Q-REC-W1-HAB-003","F","Acepto que mis rutinas actuales no favorecen completamente la convivencia familiar."),
("Q-REC-W1-HAB-004","M","Siempre cumplo todos mis compromisos familiares sin excepción ni demora.",True),
("Q-REC-W1-HAB-005","E","Me pregunto qué hábitos cotidianos generan tensión o desconexión en mi familia."),
("Q-REC-W1-HAB-006","C","Mi rutina diaria favorece la convivencia y el bienestar colectivo familiar."),
("Q-REC-W1-HAB-007","A","Noto que tengo la costumbre de revisar el celular en los momentos de convivencia."),
("Q-REC-W1-HAB-008","F","Reconozco que algunos de mis hábitos crean fricciones invisibles en el hogar."),
("Q-REC-W1-HAB-009","M","Nunca el uso de la tecnología interfiere con mi presencia familiar.",True),
("Q-REC-W1-HAB-010","E","Observo cuáles son los hábitos familiares que más fortalecen nuestra conexión."),
("Q-REC-W1-HAB-011","C","Participo activamente en las responsabilidades compartidas del hogar."),
("Q-REC-W1-HAB-012","A","Noto si evito tareas del hogar cuando estoy cansado o de mal humor."),
("Q-REC-W1-HAB-013","F","Acepto que algunos hábitos aprendidos en mi familia de origen limitan mi convivencia."),
("Q-REC-W1-HAB-014","M","En nuestra familia todos cumplen siempre sus responsabilidades sin recordatorio.",True),
("Q-REC-W1-HAB-015","E","Me pregunto qué hábitos nuevos tendrían mayor impacto en nuestra convivencia."),
("Q-REC-W1-HAB-016","C","Identifico cuando mis hábitos de consumo como pantallas o trabajo afectan la vida familiar."),
("Q-REC-W1-HAB-017","A","Noto si el hábito del reclamo se ha vuelto mi forma automática de relacionarme."),
("Q-REC-W1-HAB-018","F","Reconozco que cambiar hábitos familiares requiere consistencia y paciencia activa."),
("Q-REC-W1-HAB-019","A","Me doy cuenta de que llego a casa en modo automático sin presencia consciente."),
("Q-REC-W1-HAB-020","F","Percibo cuáles hábitos del hogar generan paz y cuáles generan ansiedad o tensión."),
("Q-REC-W1-HAB-021","C","Acepto que soy modelo de hábitos para los demás miembros de mi familia."),
("Q-REC-W1-HAB-022","A","Noto si mis hábitos de descanso me permiten estar disponible para mi familia."),
("Q-REC-W1-HAB-023","F","Identifico qué rutinas del hogar se hacen mecánicamente sin presencia ni conciencia."),
("Q-REC-W1-HAB-024","A","Me doy cuenta de que pospongo conversaciones importantes por falta de hábito."),
("Q-REC-W1-HAB-025","F","Reconozco que los hábitos familiares saludables se construyen con voluntad y práctica."),
("Q-REC-W1-HAB-026","C","Observo si mis hábitos de alimentación y descanso afectan mi disposición familiar."),
("Q-REC-W1-HAB-027","A","Noto si el hábito del trabajo excesivo desplaza mi presencia real en el hogar."),
("Q-REC-W1-HAB-028","F","Acepto que establecer nuevos hábitos familiares es un proceso gradual y colectivo."),
("Q-REC-W1-HAB-029","M","Todos mis hábitos personales son perfectamente compatibles con la paz familiar.",True),
("Q-REC-W1-HAB-030","E","Me pregunto cómo mis hábitos cotidianos están modelando el aprendizaje de mis hijos."),
# ═══ W1 TIEMPOS ═══
("Q-REC-W1-TIE-001","C","Estoy realmente presente cuando comparto tiempo familiar sin distracciones."),
("Q-REC-W1-TIE-002","A","Noto que el trabajo o el celular absorben gran parte de mi atención en casa."),
("Q-REC-W1-TIE-003","F","Acepto que no siempre estoy disponible emocionalmente cuando estoy físicamente en casa."),
("Q-REC-W1-TIE-004","M","Siempre dedico tiempo de calidad total a mi familia sin ninguna distracción.",True),
("Q-REC-W1-TIE-005","E","Observo cuánto tiempo real de conexión profunda tengo con cada miembro familiar."),
("Q-REC-W1-TIE-006","C","Reservo espacios conscientes para escuchar y estar presente con mi familia."),
("Q-REC-W1-TIE-007","A","Noto que la sensación de falta de tiempo es una presión mental constante en mi vida."),
("Q-REC-W1-TIE-008","F","Reconozco que el tiempo que paso en casa no siempre equivale a presencia real."),
("Q-REC-W1-TIE-009","M","En nuestra familia siempre tenemos tiempo de calidad abundante sin presiones.",True),
("Q-REC-W1-TIE-010","E","Me pregunto cuántos momentos del día convierto en oportunidades de conexión familiar."),
("Q-REC-W1-TIE-011","C","Identifico la diferencia entre estar ocupado por la familia y estar disponible para ella."),
("Q-REC-W1-TIE-012","A","Noto si acelero el ritmo de los demás para que se ajuste al mío propio."),
("Q-REC-W1-TIE-013","F","Acepto que la calidad del tiempo familiar importa más que la cantidad de horas."),
("Q-REC-W1-TIE-014","A","Me doy cuenta de que postergo momentos familiares por urgencias laborales frecuentes."),
("Q-REC-W1-TIE-015","F","Percibo el valor de 5 minutos de presencia plena frente a una hora de distracción."),
("Q-REC-W1-TIE-016","C","Reconozco cuando uso el tiempo libre como huida en lugar de como encuentro familiar."),
("Q-REC-W1-TIE-017","A","Noto si mi organización del tiempo incluye o excluye espacios reales para la familia."),
("Q-REC-W1-TIE-018","F","Identifico los momentos en que podría estar más presente pero elijo no estarlo."),
("Q-REC-W1-TIE-019","A","Me doy cuenta de que rara vez tengo momentos sin pantallas con mi familia."),
("Q-REC-W1-TIE-020","F","Acepto que gestionar mejor mi tiempo es una forma concreta de demostrar amor familiar."),
("Q-REC-W1-TIE-021","C","Observo si el descanso que tomo en casa es individual o compartido con mi familia."),
("Q-REC-W1-TIE-022","A","Noto si priorizo el ocio personal por encima de la convivencia familiar activa."),
("Q-REC-W1-TIE-023","F","Reconozco que el tiempo sin pantallas es una inversión en el vínculo familiar."),
("Q-REC-W1-TIE-024","A","Me doy cuenta de que llego tarde o ausente a momentos importantes de la familia."),
("Q-REC-W1-TIE-025","F","Percibo si existe desequilibrio entre el tiempo que doy al trabajo y a mi familia."),
("Q-REC-W1-TIE-026","C","Acepto que la presencia consciente con mi familia requiere decidirlo activamente."),
("Q-REC-W1-TIE-027","A","Noto si el cansancio acumulado me impide participar activamente en la vida familiar."),
("Q-REC-W1-TIE-028","F","Identifico cuáles actividades familiares me generan genuino bienestar y conexión."),
("Q-REC-W1-TIE-029","M","Nunca hay momentos en que no esté completamente disponible para mi familia.",True),
("Q-REC-W1-TIE-030","E","Me pregunto cómo redistribuiría mi tiempo si el bienestar familiar fuera mi prioridad."),
# ═══ M1 EMOCIONES ═══
("Q-REC-M1-EMO-001","C","Comienzo a identificar los patrones emocionales repetitivos que generan conflictos."),
("Q-REC-M1-EMO-002","A","Noto que mis emociones han comenzado a influir menos en mis reacciones automáticas."),
("Q-REC-M1-EMO-003","F","Percibo con más claridad cómo mi historia emocional personal moldea la dinámica familiar."),
("Q-REC-M1-EMO-004","M","Ya he resuelto todos mis conflictos emocionales y no tengo trabajo pendiente.",True),
("Q-REC-M1-EMO-005","E","Observo cuáles emociones del pasado aún no he procesado y siguen activas en casa."),
("Q-REC-M1-EMO-006","C","Identifico el momento exacto antes de reaccionar emocionalmente de forma impulsiva."),
("Q-REC-M1-EMO-007","A","Me doy cuenta de cómo mis reacciones emocionales están conectadas con mis necesidades."),
("Q-REC-M1-EMO-008","F","Acepto que el trabajo emocional personal es indispensable para la salud familiar."),
("Q-REC-M1-EMO-009","A","Noto si mis emociones de frustración o tristeza están siendo ignoradas o reprimidas."),
("Q-REC-M1-EMO-010","F","Reconozco la diferencia entre sentir una emoción y actuar automáticamente desde ella."),
("Q-REC-M1-EMO-011","C","Puedo nombrar con precisión al menos cinco emociones distintas que experimento en casa."),
("Q-REC-M1-EMO-012","A","Noto si el ambiente emocional del hogar está mejorando o empeorando gradualmente."),
("Q-REC-M1-EMO-013","F","Identifico cuándo uso la racionalización para evitar sentir emociones difíciles."),
("Q-REC-M1-EMO-014","M","Considero que mis emociones no tienen ningún impacto en el bienestar de mi familia.",True),
("Q-REC-M1-EMO-015","E","Me pregunto qué emociones necesito trabajar para contribuir mejor a mi familia."),
("Q-REC-M1-EMO-016","C","Reconozco cuando el miedo o la ansiedad están disfrazados de enojo en mis reacciones."),
("Q-REC-M1-EMO-017","A","Noto si hay vergüenza o culpa no resuelta que afecta mi forma de relacionarme en casa."),
("Q-REC-M1-EMO-018","F","Percibo cómo la atmósfera emocional de este mes ha evolucionado desde que comencé el proceso."),
("Q-REC-M1-EMO-019","A","Me doy cuenta de que ciertas palabras o situaciones me desregulan emocionalmente."),
("Q-REC-M1-EMO-020","F","Acepto que el bienestar emocional familiar es una construcción diaria y consciente."),
("Q-REC-M1-EMO-021","C","Identifico si estoy comenzando a regularme mejor antes de que escalen los conflictos."),
("Q-REC-M1-EMO-022","A","Noto que mi apertura emocional con la familia ha aumentado aunque sea sutilmente."),
("Q-REC-M1-EMO-023","F","Reconozco cuándo necesito apoyo emocional externo para sostener el proceso familiar."),
("Q-REC-M1-EMO-024","M","Creo que ya he avanzado suficiente y no necesito seguir trabajando mis emociones.",True),
("Q-REC-M1-EMO-025","E","Observo si los demás miembros de mi familia perciben cambios en mi estado emocional."),
("Q-REC-M1-EMO-026","C","Acepto que hay ciclos emocionales difíciles que forman parte del proceso de cambio."),
("Q-REC-M1-EMO-027","A","Noto si la comunicación emocional en casa es más fluida que en la semana inicial."),
("Q-REC-M1-EMO-028","A","Me doy cuenta de que los momentos de calma son ahora más frecuentes que antes.",False,True),
# ═══ M1 COMUNICACION ═══
("Q-REC-M1-COM-001","C","Comienzo a escuchar con más intención y menos defensa en las conversaciones familiares."),
("Q-REC-M1-COM-002","A","Noto que las conversaciones difíciles ya no terminan siempre en discusión o silencio."),
("Q-REC-M1-COM-003","F","Percibo una ligera mejora en la calidad de cómo me expreso cuando estoy molesto."),
("Q-REC-M1-COM-004","M","Mi comunicación familiar siempre ha sido perfecta y no necesita ningún ajuste.",True),
("Q-REC-M1-COM-005","E","Me pregunto qué tipo de conversaciones le hacen falta a nuestra familia para conectar."),
("Q-REC-M1-COM-006","C","Identifico cuando estoy usando la comunicación para controlar en lugar de conectar."),
("Q-REC-M1-COM-007","A","Noto que he comenzado a reducir los reproches y las generalizaciones en mis reclamos."),
("Q-REC-M1-COM-008","F","Reconozco que construir comunicación sana requiere sostener el esfuerzo con constancia."),
("Q-REC-M1-COM-009","A","Me doy cuenta de que empiezo a preguntar más y a suponer menos en las conversaciones."),
("Q-REC-M1-COM-010","F","Acepto que la escucha activa es una habilidad que necesito practicar conscientemente."),
("Q-REC-M1-COM-011","C","Puedo identificar si una conversación está construyendo o destruyendo el vínculo familiar."),
("Q-REC-M1-COM-012","A","Noto que ya no huyo de todas las conversaciones difíciles como antes lo hacía."),
("Q-REC-M1-COM-013","F","Percibo el impacto que mis palabras tienen en el estado emocional de los demás."),
("Q-REC-M1-COM-014","M","En nuestra familia todos siempre se expresan con amor y sin fricción comunicativa.",True),
("Q-REC-M1-COM-015","E","Observo qué tipo de lenguaje uso cuando estoy bajo presión o estrés en casa."),
("Q-REC-M1-COM-016","C","Reconozco la diferencia entre comunicarme desde el amor y hacerlo desde el miedo."),
("Q-REC-M1-COM-017","A","Noto si hay temas específicos que generan conflicto sistemáticamente al abordarlos."),
("Q-REC-M1-COM-018","F","Identifico cuándo soy yo quien cierra la comunicación con mi actitud o silencio."),
("Q-REC-M1-COM-019","A","Me doy cuenta de que estoy comenzando a validar las emociones de los demás más."),
("Q-REC-M1-COM-020","F","Acepto que los malentendidos en casa nacen muchas veces de mis suposiciones no verificadas."),
("Q-REC-M1-COM-021","C","Identifico si estoy empezando a pedir lo que necesito con más claridad y menos queja."),
("Q-REC-M1-COM-022","A","Noto que los momentos de diálogo tranquilo son más frecuentes que hace un mes."),
("Q-REC-M1-COM-023","F","Reconozco que mejorar la comunicación familiar es un proceso con avances y retrocesos."),
("Q-REC-M1-COM-024","M","Considero que ya domino completamente el arte de comunicarme en mi familia.",True),
("Q-REC-M1-COM-025","E","Me pregunto cuántas conversaciones importantes aún evito tener por miedo o incomodidad."),
("Q-REC-M1-COM-026","A","Noto si he comenzado a usar más palabras que construyen y menos que lastiman."),
("Q-REC-M1-COM-027","F","Percibo si la familia en general habla con más apertura que en la etapa inicial."),
("Q-REC-M1-COM-028","A","Me doy cuenta de que escuchar sin interrumpir me está resultando menos difícil.",False,True),
# ═══ M1 HABITOS ═══
("Q-REC-M1-HAB-001","C","Comienzo a establecer rutinas más consistentes que favorecen la convivencia familiar."),
("Q-REC-M1-HAB-002","A","Noto que algunos hábitos negativos están siendo reemplazados aunque sea parcialmente."),
("Q-REC-M1-HAB-003","F","Percibo que la constancia en pequeñas acciones tiene un impacto real en el hogar."),
("Q-REC-M1-HAB-004","M","Mis hábitos familiares siempre han sido perfectos y nunca han generado problemas.",True),
("Q-REC-M1-HAB-005","E","Me pregunto cuáles nuevos hábitos podrían tener mayor impacto en nuestra familia."),
("Q-REC-M1-HAB-006","C","Identifico los hábitos que necesito mantener y los que necesito transformar aún."),
("Q-REC-M1-HAB-007","A","Noto que el tiempo con pantallas ha disminuido aunque sea ligeramente en nuestra casa."),
("Q-REC-M1-HAB-008","F","Reconozco la importancia de rituales familiares pequeños y su poder de conexión."),
("Q-REC-M1-HAB-009","A","Me doy cuenta de que empiezo a cumplir más acuerdos que antes dejaba pasar."),
("Q-REC-M1-HAB-010","F","Acepto que construir hábitos nuevos toma tiempo y requiere paciencia con uno mismo."),
("Q-REC-M1-HAB-011","C","Puedo identificar al menos tres hábitos que han mejorado desde que comenzó el proceso."),
("Q-REC-M1-HAB-012","A","Noto que la organización del espacio familiar refleja el orden interno que trabajamos."),
("Q-REC-M1-HAB-013","F","Percibo que los rituales de saludo y despedida empiezan a ser más presentes y cálidos."),
("Q-REC-M1-HAB-014","M","En nuestra familia todos hemos logrado perfectamente todos los hábitos requeridos.",True),
("Q-REC-M1-HAB-015","E","Observo cuáles hábitos se mantienen con facilidad y cuáles requieren más esfuerzo."),
("Q-REC-M1-HAB-016","C","Reconozco si estoy modelando comportamientos saludables para los demás en el hogar."),
("Q-REC-M1-HAB-017","A","Noto si empiezo a ser más consistente con los compromisos que hago en familia."),
("Q-REC-M1-HAB-018","F","Identifico que los pequeños cambios de hábito generan grandes transformaciones con tiempo."),
("Q-REC-M1-HAB-019","A","Me doy cuenta de que empiezo a responder de forma más consciente y menos automática."),
("Q-REC-M1-HAB-020","F","Acepto que hay hábitos muy arraigados que necesitarán más tiempo para transformarse."),
("Q-REC-M1-HAB-021","C","Observo si las responsabilidades del hogar se distribuyen de forma más equitativa ahora."),
("Q-REC-M1-HAB-022","A","Noto si el orden y el ambiente del hogar reflejan el estado emocional colectivo."),
("Q-REC-M1-HAB-023","F","Reconozco que la pausa antes de reaccionar es un hábito que está comenzando a crecer."),
("Q-REC-M1-HAB-024","A","Me doy cuenta de que dedicar tiempo a la familia se está volviendo más prioritario."),
("Q-REC-M1-HAB-025","E","Me pregunto qué hábito específico, si lo cambiara hoy, transformaría más la familia."),
("Q-REC-M1-HAB-026","A","Noto si los hábitos que pedimos a los hijos son coherentes con los que practicamos."),
("Q-REC-M1-HAB-027","A","Me doy cuenta de que la consistencia en el proceso empieza a dar sus primeros frutos.",False,True),
# ═══ M1 TIEMPOS ═══
("Q-REC-M1-TIE-001","C","Comienzo a reservar tiempo real de calidad para la convivencia familiar cada semana."),
("Q-REC-M1-TIE-002","A","Noto que la presión del tiempo sigue siendo alta pero ya no invade todo mi espacio."),
("Q-REC-M1-TIE-003","F","Percibo la diferencia entre tiempo de calidad y tiempo de cantidad en casa."),
("Q-REC-M1-TIE-004","M","Siempre tengo suficiente tiempo y nunca descuido a mi familia por trabajo u otras causas.",True),
("Q-REC-M1-TIE-005","E","Me pregunto cómo organizaría mi semana si la familia fuera realmente mi prioridad."),
("Q-REC-M1-TIE-006","C","Identifico si estoy comenzando a crear pequeños rituales de tiempo familiar consistentes."),
("Q-REC-M1-TIE-007","A","Noto que los momentos sin tecnología están aumentando gradualmente en nuestra casa."),
("Q-REC-M1-TIE-008","F","Reconozco que la presencia consciente no necesita ser larga sino genuinamente real."),
("Q-REC-M1-TIE-009","A","Me doy cuenta de que algunas actividades familiares ahora me generan conexión real."),
("Q-REC-M1-TIE-010","F","Acepto que priorizar el tiempo familiar requiere decir 'no' a otras demandas activas."),
("Q-REC-M1-TIE-011","C","Puedo identificar al menos un ritual de tiempo familiar que estamos construyendo juntos."),
("Q-REC-M1-TIE-012","A","Noto si el tiempo de descanso personal y el tiempo familiar están más equilibrados."),
("Q-REC-M1-TIE-013","F","Percibo que los momentos familiares espontáneos empiezan a aparecer con más frecuencia."),
("Q-REC-M1-TIE-014","M","En nuestra familia nunca hay conflictos relacionados con el tiempo o las ausencias.",True),
("Q-REC-M1-TIE-015","E","Observo qué actividades familiares generan los recuerdos más significativos para todos."),
("Q-REC-M1-TIE-016","C","Reconozco si estoy comenzando a llegar más presente y menos acelerado a los momentos."),
("Q-REC-M1-TIE-017","A","Noto que la calidad de mi presencia durante las comidas familiares ha mejorado algo."),
("Q-REC-M1-TIE-018","F","Identifico los momentos del día que podrían convertirse en rituales de conexión."),
("Q-REC-M1-TIE-019","A","Me doy cuenta de que reducir el tiempo de pantallas requiere esfuerzo pero es posible."),
("Q-REC-M1-TIE-020","F","Acepto que el tiempo invertido en familia tiene un retorno invisible pero profundo."),
("Q-REC-M1-TIE-021","C","Observo si los acuerdos sobre el uso del tiempo en casa son claros y respetados."),
("Q-REC-M1-TIE-022","A","Noto si el tiempo que comparto con mi pareja se está fortaleciendo gradualmente."),
("Q-REC-M1-TIE-023","F","Reconozco que la consistencia en los rituales de tiempo familiar genera seguridad."),
("Q-REC-M1-TIE-024","A","Me doy cuenta de que pequeños momentos conscientes acumulados transforman la familia."),
("Q-REC-M1-TIE-025","F","Percibo si la familia siente que existe más tiempo de calidad compartido que antes."),
("Q-REC-M1-TIE-026","M","Siempre organizo perfectamente el tiempo para que nunca falte nada ni nadie.",True),
("Q-REC-M1-TIE-027","E","Me pregunto qué actividad familiar nueva podríamos crear para fortalecer nuestros vínculos."),
]

def build(raw):
    out=[]
    for item in raw:
        qid,tc,text=item[0],item[1],item[2]
        rev=item[3] if len(item)>3 else False
        rel=item[4] if len(item)>4 else False
        pil,mil,dim,ph,sw,mg,rt,cat=meta(qid)
        out.append({
            "id":qid,"text":text,
            "pillarName":pil,"milestoneCode":mil,"dimension":dim,
            "type":TT[tc],"phase":ph,"memberType":"familia",
            "severityWeight":sw,"detectsRelapse":rel,
            "reverseQuestion":rev,"requiresEvidence":False,
            "category":cat,"riskType":rt,"missionGenerator":mg,
            "adaptiveTriggers":None,"evidenceType":None
        })
    return out

out_path=os.path.join(os.path.dirname(__file__),"questions_part1.json")
data={"version":"2.0-part1","count":len(R),"questions":build(R)}
with open(out_path,"w",encoding="utf-8") as f:
    json.dump(data,f,ensure_ascii=False,indent=2)
print(f"OK Generadas {len(R)} preguntas -> {out_path}")
