#!/usr/bin/env python3
"""Genera questions_part4.json — M18+M24+M30+M36 (340 preguntas)"""
import json, os, sys
sys.path.insert(0,os.path.dirname(__file__))
from gen_questions_p1 import meta, TT, build

R=[
# ═══ M18 EMOCIONES (22) — Crecimiento Generacional ═══
("Q-ENT-M18-EMO-001","C","Vivo un estado emocional de paz que se irradia hacia toda mi familia y entorno cercano."),
("Q-ENT-M18-EMO-002","A","Noto que los patrones emocionales sanos que cultivé ya se reflejan en mis hijos y familiares."),
("Q-ENT-M18-EMO-003","F","Percibo que nuestra familia ha desarrollado una inteligencia emocional colectiva y generacional."),
("Q-ENT-M18-EMO-004","M","Nunca tengo emociones difíciles porque el proceso ya me liberó completamente de ellas.",True),
("Q-ENT-M18-EMO-005","E","Observo qué herencias emocionales positivas estamos transmitiendo ya a las nuevas generaciones."),
("Q-ENT-M18-EMO-006","C","Sostengo la generosidad emocional incluso cuando no recibo nada a cambio de mi entrega."),
("Q-ENT-M18-EMO-007","A","Noto que la familia en su conjunto ha empezado a ser un recurso emocional para otros fuera del hogar."),
("Q-ENT-M18-EMO-008","F","He trascendido la reactividad emocional y vivo desde la elección consciente de forma consistente."),
("Q-ENT-M18-EMO-009","A","Me doy cuenta de que mis emociones ya no son respuestas al pasado sino creaciones del presente."),
("Q-ENT-M18-EMO-010","F","Acepto que el crecimiento emocional generacional es el mayor regalo que puedo dar a los míos."),
("Q-ENT-M18-EMO-011","C","Identifico que la familia puede acompañar a otras familias desde su propia experiencia de transformación."),
("Q-ENT-M18-EMO-012","A","Noto que la salud emocional familiar se está transmitiendo de forma natural a la siguiente generación."),
("Q-ENT-M18-EMO-013","F","Reconozco que dieciocho meses de trabajo emocional han sembrado una semilla generacional profunda."),
("Q-ENT-M18-EMO-014","M","Creo que nuestra familia ya es un modelo emocional perfecto para todas las familias del mundo.",True),
("Q-ENT-M18-EMO-015","E","Me pregunto qué aspectos emocionales necesito profundizar para crecer hacia la trascendencia."),
("Q-ENT-M18-EMO-016","C","Logro mantener la serenidad emocional ante pérdidas, cambios y crisis con una profundidad nueva."),
("Q-ENT-M18-EMO-017","A","Noto que la capacidad de amar sin condiciones se ha convertido en un rasgo familiar consolidado."),
("Q-ENT-M18-EMO-018","F","Percibo que la familia vive las emociones desde la profundidad y no desde la superficie reactiva."),
("Q-ENT-M18-EMO-019","A","Me doy cuenta de que el trabajo emocional colectivo ha transformado no solo la familia sino el entorno."),
("Q-ENT-M18-EMO-020","F","Acepto que el crecimiento emocional generacional requiere humildad, constancia y visión de largo plazo."),
("Q-ENT-M18-EMO-021","C","Puedo sostener la compasión hacia personas fuera de mi familia desde la madurez emocional alcanzada."),
("Q-ENT-M18-EMO-022","E","Me pregunto qué legado emocional quiero que mis hijos transmitan a sus propias familias en el futuro."),
# ═══ M18 COMUNICACION (22) ═══
("Q-ENT-M18-COM-001","C","La comunicación en nuestra familia es ahora un modelo que otras familias de nuestro entorno admiran."),
("Q-ENT-M18-COM-002","A","Noto que los hijos comunican con madurez y amor lo que aprendieron de nuestro ejemplo familiar."),
("Q-ENT-M18-COM-003","F","Percibo que nuestra forma de comunicarnos está generando cambios en otras familias de nuestro círculo."),
("Q-ENT-M18-COM-004","M","Nuestra comunicación familiar es perfecta y ya no necesitamos ningún tipo de trabajo adicional.",True),
("Q-ENT-M18-COM-005","E","Observo cómo podría nuestra familia usar su madurez comunicativa para servir a otras familias."),
("Q-ENT-M18-COM-006","C","Sostengo conversaciones generacionales profundas sobre valores, legado y propósito familiar."),
("Q-ENT-M18-COM-007","A","Noto que la comunicación que modelamos ha generado en los hijos adultos formas sanas de relacionarse."),
("Q-ENT-M18-COM-008","F","He desarrollado la capacidad de comunicarme con cualquier generación desde el amor y el respeto."),
("Q-ENT-M18-COM-009","A","Me doy cuenta de que hablar del legado y del propósito familiar es ahora parte de nuestras charlas."),
("Q-ENT-M18-COM-010","F","Acepto que la comunicación generacional requiere escuchar activamente a las generaciones más jóvenes."),
("Q-ENT-M18-COM-011","C","Identifico que nuestra comunicación familiar trasciende el hogar e impacta el tejido social cercano."),
("Q-ENT-M18-COM-012","A","Noto que los más jóvenes de la familia son capaces de comunicar sus valores con claridad y convicción."),
("Q-ENT-M18-COM-013","F","Reconozco que la comunicación generacional en M18 es el vehículo del legado familiar."),
("Q-ENT-M18-COM-014","M","Creo que todos en mi familia se comunican perfectamente en todas las situaciones posibles.",True),
("Q-ENT-M18-COM-015","E","Me pregunto qué conversaciones generacionales necesito tener para sembrar mejor el legado."),
("Q-ENT-M18-COM-016","C","Logro comunicar con claridad y amor los valores y la visión que quiero legar a mis hijos."),
("Q-ENT-M18-COM-017","A","Noto que la familia puede comunicar las historias difíciles del pasado como fuentes de aprendizaje."),
("Q-ENT-M18-COM-018","F","Percibo que nuestra forma de comunicar el amor es ya una herencia que las nuevas generaciones reciben."),
("Q-ENT-M18-COM-019","A","Me doy cuenta de que las conversaciones de legado y propósito nos unen más que cualquier actividad."),
("Q-ENT-M18-COM-020","F","Acepto que comunicar el propósito familiar de forma clara es una responsabilidad generacional."),
("Q-ENT-M18-COM-021","C","Puedo narrar la historia de nuestra familia de una forma que inspire a las generaciones más jóvenes."),
("Q-ENT-M18-COM-022","E","Me pregunto qué historias de transformación de nuestra familia necesitan ser contadas y transmitidas."),
# ═══ M18 HABITOS (21) ═══
("Q-ENT-M18-HAB-001","C","Los hábitos de nuestra familia son ahora una semilla generacional que se transmite con naturalidad."),
("Q-ENT-M18-HAB-002","A","Noto que los hijos mayores practican en sus propias vidas los hábitos que les modelamos."),
("Q-ENT-M18-HAB-003","F","Percibo que los hábitos de conciencia familiar ya trascienden el hogar e impactan al entorno."),
("Q-ENT-M18-HAB-004","M","Todos mis hábitos son perfectos y ya no necesito ningún ajuste ni trabajo adicional.",True),
("Q-ENT-M18-HAB-005","E","Observo qué hábitos de legado y servicio podríamos añadir en esta etapa de crecimiento generacional."),
("Q-ENT-M18-HAB-006","C","Sostengo hábitos de cuidado de la memoria familiar como fotografías, historias y tradiciones."),
("Q-ENT-M18-HAB-007","A","Noto que los hábitos de generosidad y servicio se están convirtiendo en un rasgo familiar distintivo."),
("Q-ENT-M18-HAB-008","F","He integrado hábitos de reflexión generacional que conectan el pasado, el presente y el futuro."),
("Q-ENT-M18-HAB-009","A","Me doy cuenta de que los rituales familiares que creamos ya forman parte de la identidad de los hijos."),
("Q-ENT-M18-HAB-010","F","Acepto que los hábitos de esta etapa tienen un impacto que va más allá de mi generación."),
("Q-ENT-M18-HAB-011","C","Identifico que los hábitos que modelamos son la herencia más duradera que podemos dejar."),
("Q-ENT-M18-HAB-012","A","Noto que los hábitos de presencia y conexión están siendo adoptados por la familia extensa."),
("Q-ENT-M18-HAB-013","F","Reconozco que en dieciocho meses hemos construido hábitos que trascenderán nuestra generación."),
("Q-ENT-M18-HAB-014","M","Considero que todos nuestros hábitos son perfectos modelos para cualquier familia.",True),
("Q-ENT-M18-HAB-015","E","Me pregunto qué hábitos de servicio y contribución podríamos practicar como familia."),
("Q-ENT-M18-HAB-016","C","Logro mantener hábitos de crecimiento personal que alimentan mi capacidad de dar a la familia."),
("Q-ENT-M18-HAB-017","A","Noto que los hábitos de gratitud y celebración son ya parte del ADN de nuestra familia."),
("Q-ENT-M18-HAB-018","F","Percibo que los hábitos de la etapa de Entrega son más amplios y trascienden el hogar."),
("Q-ENT-M18-HAB-019","A","Me doy cuenta de que los hábitos que transmitimos definen quién será la próxima generación."),
("Q-ENT-M18-HAB-020","F","Acepto que los hábitos de legado requieren intencionalidad, constancia y visión de largo plazo."),
("Q-ENT-M18-HAB-021","E","Me pregunto qué nuevos hábitos de legado y trascendencia queremos cultivar como familia."),
# ═══ M18 TIEMPOS (20) ═══
("Q-ENT-M18-TIE-001","C","El tiempo familiar es ahora un espacio sagrado donde se construye el legado generacional."),
("Q-ENT-M18-TIE-002","A","Noto que invertir tiempo en las nuevas generaciones es una de mis prioridades más claras."),
("Q-ENT-M18-TIE-003","F","Percibo que el tiempo de calidad con los nietos o la generación siguiente siembra semillas eternas."),
("Q-ENT-M18-TIE-004","M","En nuestra familia todos tienen siempre todo el tiempo que necesitan sin ninguna queja.",True),
("Q-ENT-M18-TIE-005","E","Observo cómo el tiempo que comparto con distintas generaciones moldea el futuro de la familia."),
("Q-ENT-M18-TIE-006","C","Sostengo rituales de tiempo intergeneracional que conectan lo que fue con lo que vendrá."),
("Q-ENT-M18-TIE-007","A","Noto que el tiempo dedicado a contar la historia familiar crea identidad y arraigo en los jóvenes."),
("Q-ENT-M18-TIE-008","F","He desarrollado la capacidad de vivir plenamente el presente mientras construyo el futuro familiar."),
("Q-ENT-M18-TIE-009","A","Me doy cuenta de que cada momento compartido con las nuevas generaciones es una siembra de legado."),
("Q-ENT-M18-TIE-010","F","Acepto que el tiempo generacional bien invertido es la herencia más duradera que puedo dejar."),
("Q-ENT-M18-TIE-011","C","Identifico que el tiempo intergeneracional fortalece la identidad y el sentido de pertenencia."),
("Q-ENT-M18-TIE-012","A","Noto que las nuevas generaciones de mi familia valoran el tiempo compartido con los mayores."),
("Q-ENT-M18-TIE-013","F","Reconozco que el tiempo que damos en esta etapa ya trasciende nuestra propia existencia."),
("Q-ENT-M18-TIE-014","M","Siempre tengo tiempo abundante y nunca fallan mis compromisos generacionales.",True),
("Q-ENT-M18-TIE-015","E","Me pregunto cómo quiero que las generaciones futuras recuerden el tiempo que pasamos juntos."),
("Q-ENT-M18-TIE-016","C","Logro presenciar los momentos de crecimiento de las nuevas generaciones con plena atención."),
("Q-ENT-M18-TIE-017","A","Noto que el tiempo que dedico a enseñar a través del ejemplo es el más valioso de todos."),
("Q-ENT-M18-TIE-018","F","Percibo que el tiempo generacional que vivimos es el tejido con el que se construye el legado."),
("Q-ENT-M18-TIE-019","A","Me doy cuenta de que estar presente para las nuevas generaciones es un acto de amor trascendente."),
("Q-ENT-M18-TIE-020","E","Me pregunto qué rituales de tiempo intergeneracional podríamos crear para el próximo año."),
# ═══ M24 EMOCIONES (22) — Legado Familiar ═══
("Q-ENT-M24-EMO-001","C","Las nuevas generaciones están aprendiendo hábitos emocionales sanos de nuestra familia."),
("Q-ENT-M24-EMO-002","A","Noto que el legado emocional que sembramos ya da frutos visibles en los hijos y nietos."),
("Q-ENT-M24-EMO-003","F","Nuestra convivencia emocional inspira confianza y estabilidad en quienes nos rodean."),
("Q-ENT-M24-EMO-004","M","Nuestra familia tiene un legado emocional perfectamente establecido sin ninguna área oscura.",True),
("Q-ENT-M24-EMO-005","E","Observo cuáles aspectos del legado emocional familiar aún necesitan ser trabajados y sellados."),
("Q-ENT-M24-EMO-006","C","Sostengo la práctica de transmitir conscientemente la salud emocional a las generaciones futuras."),
("Q-ENT-M24-EMO-007","A","Noto que la familia vive las emociones con una profundidad que hace dos años era impensable."),
("Q-ENT-M24-EMO-008","F","Estamos construyendo una cultura familiar de consciencia emocional que trasciende nuestra vida."),
("Q-ENT-M24-EMO-009","A","Me doy cuenta de que el amor familiar que cultivamos es ya una fuerza transformadora para otros."),
("Q-ENT-M24-EMO-010","F","Acepto que el legado emocional requiere que yo siga trabajando mi propio crecimiento personal."),
("Q-ENT-M24-EMO-011","C","Identifico que la salud emocional familiar es ahora un bien que compartimos con el entorno."),
("Q-ENT-M24-EMO-012","A","Noto que los hijos y nietos han internalizado el vocabulario emocional que sembramos en casa."),
("Q-ENT-M24-EMO-013","F","Reconozco que dos años de transformación emocional han tejido un legado que trasciende el tiempo."),
("Q-ENT-M24-EMO-014","M","Creo que nuestra familia ya tiene el legado emocional completo y perfecto.",True),
("Q-ENT-M24-EMO-015","E","Me pregunto cómo la historia emocional de nuestra familia inspirará a las familias del futuro."),
("Q-ENT-M24-EMO-016","C","Logro vivir en un estado de amor y gratitud que se convierte en fuente de vida para los demás."),
("Q-ENT-M24-EMO-017","A","Noto que la familia puede acompañar procesos de dolor ajenos desde una madurez emocional real."),
("Q-ENT-M24-EMO-018","F","Percibo que el legado emocional de nuestra familia ya está presente en otras generaciones."),
("Q-ENT-M24-EMO-019","A","Me doy cuenta de que la forma en que vivimos las emociones define quiénes somos como familia."),
("Q-ENT-M24-EMO-020","F","Acepto que transmitir un legado emocional sano es la mayor responsabilidad de esta etapa."),
("Q-ENT-M24-EMO-021","C","Puedo articular con claridad el legado emocional que quiero dejar a las generaciones futuras."),
("Q-ENT-M24-EMO-022","E","Me pregunto de qué manera el legado emocional que sembramos hoy cambiará a las familias del futuro."),
# ═══ M24 COMUNICACION (22) ═══
("Q-ENT-M24-COM-001","C","Nuestra comunicación familiar es ahora un legado vivo que las generaciones jóvenes ya practican."),
("Q-ENT-M24-COM-002","A","Noto que las historias de transformación de nuestra familia son narradas por los más jóvenes."),
("Q-ENT-M24-COM-003","F","La forma en que nos comunicamos en familia ya es una enseñanza que trasciende el hogar."),
("Q-ENT-M24-COM-004","M","Nuestra familia tiene una comunicación perfecta que ya no necesita ningún tipo de atención.",True),
("Q-ENT-M24-COM-005","E","Observo qué aspectos de nuestra comunicación generacional podríamos mejorar o profundizar."),
("Q-ENT-M24-COM-006","C","Sostengo conversaciones de legado donde compartimos la visión y los valores familiares."),
("Q-ENT-M24-COM-007","A","Noto que la comunicación que modelamos durante dos años ya vive en quienes nos observaron."),
("Q-ENT-M24-COM-008","F","Estamos construyendo un lenguaje familiar que identifica quiénes somos y hacia dónde vamos."),
("Q-ENT-M24-COM-009","A","Me doy cuenta de que las conversaciones más importantes de nuestra familia hablan del legado."),
("Q-ENT-M24-COM-010","F","Acepto que el legado comunicativo familiar se transmite más con el ejemplo que con las palabras."),
("Q-ENT-M24-COM-011","C","Identifico que nuestra forma de comunicarnos ya ha influido en la comunicación de otras familias."),
("Q-ENT-M24-COM-012","A","Noto que los jóvenes de la familia articulan con claridad los valores familiares en sus conversaciones."),
("Q-ENT-M24-COM-013","F","Reconozco que la comunicación del legado requiere honestidad sobre el pasado y esperanza sobre el futuro."),
("Q-ENT-M24-COM-014","M","Creo que la comunicación de nuestra familia es ya un modelo perfecto sin área de mejora.",True),
("Q-ENT-M24-COM-015","E","Me pregunto qué conversaciones generacionales quedan pendientes antes de llegar a la Trascendencia."),
("Q-ENT-M24-COM-016","C","Logro comunicar el amor familiar de forma que trasciende las diferencias generacionales."),
("Q-ENT-M24-COM-017","A","Noto que hablar de errores del pasado se ha convertido en una fuente de aprendizaje familiar."),
("Q-ENT-M24-COM-018","F","Percibo que las narrativas familiares que contamos refuerzan la identidad y el propósito colectivo."),
("Q-ENT-M24-COM-019","A","Me doy cuenta de que el relato que hacemos de nuestra familia define cómo nos veremos en el futuro."),
("Q-ENT-M24-COM-020","F","Acepto que el legado comunicativo más valioso es el ejemplo de amor honesto que vivimos cada día."),
("Q-ENT-M24-COM-021","C","Puedo contar la historia de nuestra familia con orgullo, honestidad y esperanza plena."),
("Q-ENT-M24-COM-022","E","Me pregunto qué palabras quiero que mis hijos usen para describir nuestra familia en veinte años."),
# ═══ M24 HABITOS (21) ═══
("Q-ENT-M24-HAB-001","C","Los hábitos que cultivamos durante dos años ya son parte del ADN de las nuevas generaciones."),
("Q-ENT-M24-HAB-002","A","Noto que los hábitos de gratitud, presencia y amor son ya automáticos en nuestra familia."),
("Q-ENT-M24-HAB-003","F","Estamos construyendo hábitos familiares que trascienden nuestra generación y definen el legado."),
("Q-ENT-M24-HAB-004","M","Todos los hábitos de legado están perfectamente establecidos y no necesitan revisión.",True),
("Q-ENT-M24-HAB-005","E","Observo qué hábitos de trascendencia y contribución podría incorporar la familia en este período."),
("Q-ENT-M24-HAB-006","C","Sostengo hábitos de registro y celebración de los momentos de transformación familiar."),
("Q-ENT-M24-HAB-007","A","Noto que los hábitos de dos años ya son practicados por los hijos en sus propios hogares."),
("Q-ENT-M24-HAB-008","F","He integrado el hábito de reflexionar sobre el legado que estoy construyendo en cada acto."),
("Q-ENT-M24-HAB-009","A","Me doy cuenta de que los hábitos del legado requieren consciencia del impacto a largo plazo."),
("Q-ENT-M24-HAB-010","F","Acepto que los hábitos de esta etapa tienen una dimensión espiritual y trascendente clara."),
("Q-ENT-M24-HAB-011","C","Identifico que los hábitos que transmitimos son más poderosos que cualquier herencia material."),
("Q-ENT-M24-HAB-012","A","Noto que la familia practica hábitos de servicio y contribución al entorno con más frecuencia."),
("Q-ENT-M24-HAB-013","F","Reconozco que dos años de hábitos conscientes han transformado la cultura familiar de forma profunda."),
("Q-ENT-M24-HAB-014","M","Considero que nuestra familia tiene hábitos perfectos que ya sirven de modelo universal.",True),
("Q-ENT-M24-HAB-015","E","Me pregunto cómo los hábitos que sembramos hoy vivirán en la tercera generación de nuestra familia."),
("Q-ENT-M24-HAB-016","C","Logro mantener los hábitos de legado incluso cuando las circunstancias cambian o son difíciles."),
("Q-ENT-M24-HAB-017","A","Noto que los rituales de familia que creamos han tomado vida propia más allá de nuestra intención."),
("Q-ENT-M24-HAB-018","F","Percibo que los hábitos del legado nos conectan con algo más grande que nuestra propia familia."),
("Q-ENT-M24-HAB-019","A","Me doy cuenta de que el hábito de la gratitud colectiva es un recurso espiritual inagotable."),
("Q-ENT-M24-HAB-020","F","Acepto que cultivar hábitos de trascendencia requiere una visión que va más allá del presente."),
("Q-ENT-M24-HAB-021","E","Me pregunto qué hábito, si toda la familia lo practicara, transformaría nuestra comunidad entera."),
# ═══ M24 TIEMPOS (20) ═══
("Q-ENT-M24-TIE-001","C","El tiempo que invierto con las nuevas generaciones es mi forma más concreta de construir legado."),
("Q-ENT-M24-TIE-002","A","Noto que la calidad del tiempo familiar de estos dos años ya está generando su propia historia."),
("Q-ENT-M24-TIE-003","F","Percibo que cada momento compartido con las generaciones jóvenes es una siembra que fructificará."),
("Q-ENT-M24-TIE-004","M","En nuestra familia el tiempo se distribuye perfectamente y nadie necesita más ni menos.",True),
("Q-ENT-M24-TIE-005","E","Observo cómo el tiempo que dedico a cada generación va construyendo el tejido del legado familiar."),
("Q-ENT-M24-TIE-006","C","Sostengo la práctica de presencia plena con cada miembro independientemente de la edad."),
("Q-ENT-M24-TIE-007","A","Noto que el tiempo de historias compartidas entre generaciones es un regalo que enriquece a todos."),
("Q-ENT-M24-TIE-008","F","He aprendido a vivir el tiempo como una ofrenda de amor a quienes vienen después de mí."),
("Q-ENT-M24-TIE-009","A","Me doy cuenta de que la presencia física y emocional en el tiempo es el mayor legado posible."),
("Q-ENT-M24-TIE-010","F","Acepto que el tiempo que damos a las generaciones nuevas tiene un impacto que no veremos totalmente."),
("Q-ENT-M24-TIE-011","C","Identifico que el tiempo de legado es distinto al tiempo cotidiano: es más intencional y sagrado."),
("Q-ENT-M24-TIE-012","A","Noto que los encuentros intergeneracionales que organizamos son los más recordados por todos."),
("Q-ENT-M24-TIE-013","F","Reconozco que el tiempo invertido en el legado durante dos años ya tiene frutos visibles y tangibles."),
("Q-ENT-M24-TIE-014","M","Siempre tengo todo el tiempo necesario para atender perfectamente a todas las generaciones.",True),
("Q-ENT-M24-TIE-015","E","Me pregunto qué ritual de tiempo intergeneracional podría crear que dure más que mi propia vida."),
("Q-ENT-M24-TIE-016","C","Logro estar presente en los hitos importantes de las nuevas generaciones con plena conciencia."),
("Q-ENT-M24-TIE-017","A","Noto que la familia ha aprendido a honrar el tiempo como el recurso más sagrado que tiene."),
("Q-ENT-M24-TIE-018","F","Percibo que el tiempo de legado que vivimos hoy será recordado como fundamento de la familia."),
("Q-ENT-M24-TIE-019","A","Me doy cuenta de que la calidad del tiempo que ofrezco a los míos define quién seré para ellos."),
("Q-ENT-M24-TIE-020","E","Me pregunto qué recuerdos de tiempo compartido quiero que mis descendientes cuenten en el futuro."),
# ═══ M30 EMOCIONES (19) — Trascendencia ═══
("Q-ENT-M30-EMO-001","C","Vivo en un estado de paz emocional profunda que se mantiene independientemente de las circunstancias."),
("Q-ENT-M30-EMO-002","A","Noto que las emociones ya no me controlan sino que las habito con plena conciencia y libertad."),
("Q-ENT-M30-EMO-003","F","Percibo que nuestra familia trasciende los conflictos porque hemos aprendido a verlos como regalos."),
("Q-ENT-M30-EMO-004","M","Soy completamente perfecto emocionalmente y no tengo nada más que aprender ni trabajar.",True),
("Q-ENT-M30-EMO-005","E","Observo qué dimensión del ser emocional aún no he explorado en este camino de trascendencia."),
("Q-ENT-M30-EMO-006","C","Sostengo el amor incondicional hacia todos los miembros de mi familia sin necesidad de reciprocidad."),
("Q-ENT-M30-EMO-007","A","Noto que la familia vive las transiciones y pérdidas desde una base de paz y confianza profunda."),
("Q-ENT-M30-EMO-008","F","He alcanzado un nivel de madurez emocional donde el miedo ya no dicta mis decisiones familiares."),
("Q-ENT-M30-EMO-009","A","Me doy cuenta de que la alegría que vivo en familia es una fuente de transformación para el entorno."),
("Q-ENT-M30-EMO-010","F","Acepto que la trascendencia emocional no elimina el dolor sino que lo integra con sabiduría."),
("Q-ENT-M30-EMO-011","C","Identifico que mi paz interior se ha convertido en el mayor regalo que doy a mi familia."),
("Q-ENT-M30-EMO-012","A","Noto que la familia puede sostener procesos de duelo y transición desde la serenidad y la fe."),
("Q-ENT-M30-EMO-013","F","Reconozco que dos años y medio de transformación emocional nos han llevado a una paz que no conocíamos."),
("Q-ENT-M30-EMO-014","M","Creo que nuestra familia ha logrado la trascendencia emocional total y definitiva.",True),
("Q-ENT-M30-EMO-015","E","Me pregunto cómo la paz que vivimos puede ser un servicio para otras familias en sufrimiento."),
("Q-ENT-M30-EMO-016","C","Logro mantenerme emocionalmente centrado en situaciones que antes me habrían desequilibrado totalmente."),
("Q-ENT-M30-EMO-017","A","Noto que el amor que experimento en familia ya tiene una dimensión espiritual y trascendente."),
("Q-ENT-M30-EMO-018","F","Percibo que la trascendencia emocional no es un estado fijo sino un camino que se recorre cada día."),
("Q-ENT-M30-EMO-019","E","Me pregunto qué significa para mí y mi familia llegar a la Plenitud Total en M36."),
# ═══ M30 COMUNICACION (19) ═══
("Q-ENT-M30-COM-001","C","La comunicación en nuestra familia ha trascendido las palabras y vive en el amor que practicamos."),
("Q-ENT-M30-COM-002","A","Noto que podemos comunicarnos en momentos de dolor y pérdida con profundidad y sin derrumbarnos."),
("Q-ENT-M30-COM-003","F","Percibo que nuestra familia es capaz de comunicar verdades difíciles con amor y sin daño."),
("Q-ENT-M30-COM-004","M","Nuestra comunicación es perfecta y trascendente, no hay nada más que mejorar.",True),
("Q-ENT-M30-COM-005","E","Observo de qué manera nuestra madurez comunicativa podría servir a familias en crisis."),
("Q-ENT-M30-COM-006","C","Sostengo conversaciones de trascendencia sobre el propósito, la fe y el sentido de la vida familiar."),
("Q-ENT-M30-COM-007","A","Noto que la familia habla del futuro con esperanza y del pasado con gratitud y sin resentimiento."),
("Q-ENT-M30-COM-008","F","He desarrollado la capacidad de comunicarme desde el silencio amoroso cuando las palabras no alcanzan."),
("Q-ENT-M30-COM-009","A","Me doy cuenta de que la comunicación de nuestra familia ya es un testimonio de transformación."),
("Q-ENT-M30-COM-010","F","Acepto que la trascendencia comunicativa es la capacidad de hablar del alma a través de los actos."),
("Q-ENT-M30-COM-011","C","Identifico que nuestra familia ya comunica amor de formas que van más allá de lo verbal."),
("Q-ENT-M30-COM-012","A","Noto que las generaciones jóvenes ya articulan con sabiduría los valores que sembramos en casa."),
("Q-ENT-M30-COM-013","F","Reconozco que la comunicación trascendente requiere escuchar lo que no se dice con las palabras."),
("Q-ENT-M30-COM-014","M","Creo que ya no necesitamos ningún tipo de trabajo en comunicación familiar.",True),
("Q-ENT-M30-COM-015","E","Me pregunto qué conversación de trascendencia necesita nuestra familia antes de llegar a M36."),
("Q-ENT-M30-COM-016","C","Logro comunicar el amor de una forma que toca el corazón y transforma sin necesitar esfuerzo."),
("Q-ENT-M30-COM-017","A","Noto que las palabras que usamos en familia ya reflejan la transformación profunda que vivimos."),
("Q-ENT-M30-COM-018","F","Percibo que la comunicación de nuestra familia es una expresión de la plenitud que estamos alcanzando."),
("Q-ENT-M30-COM-019","E","Me pregunto cómo nuestra historia comunicativa puede ser un regalo para las familias que vienen."),
# ═══ M30 HABITOS (19) ═══
("Q-ENT-M30-HAB-001","C","Los hábitos de nuestra familia son ahora una expresión de trascendencia y amor incondicional."),
("Q-ENT-M30-HAB-002","A","Noto que todos los hábitos saludables se practican con gozo y no con esfuerzo ni obligación."),
("Q-ENT-M30-HAB-003","F","Percibo que los hábitos que cultivamos son ya un patrimonio espiritual y emocional de la familia."),
("Q-ENT-M30-HAB-004","M","Todos los hábitos de trascendencia están perfectamente integrados sin ningún trabajo pendiente.",True),
("Q-ENT-M30-HAB-005","E","Observo qué hábitos de contemplación y silencio podríamos añadir en esta etapa de trascendencia."),
("Q-ENT-M30-HAB-006","C","Sostengo hábitos de generosidad y servicio que trascienden el núcleo familiar hacia la comunidad."),
("Q-ENT-M30-HAB-007","A","Noto que los hábitos de cuidado y presencia se practican ahora con una profundidad espiritual."),
("Q-ENT-M30-HAB-008","F","He integrado hábitos de reflexión profunda que me conectan con el propósito mayor de mi familia."),
("Q-ENT-M30-HAB-009","A","Me doy cuenta de que los hábitos de trascendencia son los que conectan lo cotidiano con lo eterno."),
("Q-ENT-M30-HAB-010","F","Acepto que en la etapa de trascendencia los hábitos son más interiores que exteriores."),
("Q-ENT-M30-HAB-011","C","Identifico que los hábitos de paz y amor que practicamos ya son una semilla que no morirá."),
("Q-ENT-M30-HAB-012","A","Noto que los rituales familiares han adquirido una dimensión sagrada que antes no tenían."),
("Q-ENT-M30-HAB-013","F","Reconozco que los hábitos de trascendencia no dependen de las circunstancias sino del ser interior."),
("Q-ENT-M30-HAB-014","M","Considero que todos mis hábitos son perfectos expresiones del amor trascendente.",True),
("Q-ENT-M30-HAB-015","E","Me pregunto qué hábitos me ayudarán a llegar a la Plenitud Total con más profundidad."),
("Q-ENT-M30-HAB-016","C","Logro vivir cada hábito cotidiano como un acto de amor y entrega más allá de mí mismo."),
("Q-ENT-M30-HAB-017","A","Noto que los hábitos de mi familia son ahora fuente de inspiración para quienes nos conocen."),
("Q-ENT-M30-HAB-018","F","Percibo que cada hábito practicado en esta etapa es una oración de amor hacia las generaciones futuras."),
("Q-ENT-M30-HAB-019","E","Me pregunto cómo los hábitos de trascendencia que vivimos hoy moldearán a las familias del mañana."),
# ═══ M30 TIEMPOS (18) ═══
("Q-ENT-M30-TIE-001","C","El tiempo ya no es una presión sino un regalo sagrado que vivo con plena conciencia."),
("Q-ENT-M30-TIE-002","A","Noto que cada momento con mi familia se vive como si fuera el último y también el primero."),
("Q-ENT-M30-TIE-003","F","Percibo que el tiempo familiar en esta etapa trasciende lo cotidiano y toca lo eterno."),
("Q-ENT-M30-TIE-004","M","Siempre vivo el tiempo con perfecta plenitud y no existen momentos perdidos en mi familia.",True),
("Q-ENT-M30-TIE-005","E","Observo cómo el tiempo que me queda puede ser usado para maximizar el legado que dejo."),
("Q-ENT-M30-TIE-006","C","Sostengo la práctica de presencia plena incluso en los momentos más ordinarios y cotidianos."),
("Q-ENT-M30-TIE-007","A","Noto que la familia vive el tiempo con una plenitud que hace dos años y medio era inimaginable."),
("Q-ENT-M30-TIE-008","F","He aprendido que el tiempo eterno vive en los momentos de amor auténtico que compartimos."),
("Q-ENT-M30-TIE-009","A","Me doy cuenta de que la prisa ha desaparecido y el presente familiar se vive con profundidad."),
("Q-ENT-M30-TIE-010","F","Acepto que el tiempo vivido en plenitud familiar es inmortal porque vive en la memoria y el amor."),
("Q-ENT-M30-TIE-011","C","Identifico que cada momento presente con mi familia es eterno porque lo viviremos para siempre."),
("Q-ENT-M30-TIE-012","A","Noto que la familia ha aprendido a vivir el tiempo como una danza sagrada entre el ser y el hacer."),
("Q-ENT-M30-TIE-013","F","Reconozco que el tiempo trascendente se vive desde el amor y no desde el reloj."),
("Q-ENT-M30-TIE-014","M","En nuestra familia todos vivimos el tiempo con perfecta plenitud y sin ninguna queja.",True),
("Q-ENT-M30-TIE-015","E","Me pregunto cómo quiero vivir los últimos seis meses hacia la Plenitud Total en M36."),
("Q-ENT-M30-TIE-016","C","Logro habitar el presente familiar con tanta intensidad que el pasado y el futuro se disuelven."),
("Q-ENT-M30-TIE-017","A","Noto que la familia celebra el tiempo juntos como el mayor privilegio de todos."),
("Q-ENT-M30-TIE-018","E","Me pregunto qué significa para mí vivir el tiempo en plena entrega durante este último tramo."),
# ═══ M36 EMOCIONES (24) — Plenitud Total ═══
("Q-ENT-M36-EMO-001","C","Vivo en una plenitud emocional que es el fruto de tres años de transformación familiar consciente."),
("Q-ENT-M36-EMO-002","A","Noto que las emociones que experimento en familia son ahora expresiones de amor maduro y pleno."),
("Q-ENT-M36-EMO-003","F","Nuestra familia ha alcanzado una plenitud emocional que es su estado natural y no un logro temporal."),
("Q-ENT-M36-EMO-004","M","Hemos alcanzado la plenitud emocional perfecta y ya no necesitamos ningún trabajo ni evolución.",True),
("Q-ENT-M36-EMO-005","E","Observo con gratitud el camino emocional recorrido y lo que aún puede seguir expandiéndose."),
("Q-ENT-M36-EMO-006","C","Sostengo la paz emocional incluso ante la adversidad, la pérdida y la incertidumbre profunda."),
("Q-ENT-M36-EMO-007","A","Noto que la familia vive en un estado de amor, gratitud y paz que ya es su forma de ser."),
("Q-ENT-M36-EMO-008","F","He integrado la plenitud emocional como el estado desde el que elijo vivir cada día de mi vida."),
("Q-ENT-M36-EMO-009","A","Me doy cuenta de que tres años de trabajo emocional han transformado quién soy en lo más profundo."),
("Q-ENT-M36-EMO-010","F","Acepto que la plenitud emocional no es el final del camino sino el inicio de una vida más plena."),
("Q-ENT-M36-EMO-011","C","Identifico que la salud emocional familiar alcanzada en M36 es el legado más puro que podemos dar."),
("Q-ENT-M36-EMO-012","A","Noto que la alegría y el amor son ya los estados emocionales dominantes de nuestra vida familiar."),
("Q-ENT-M36-EMO-013","F","Reconozco que tres años de transformación emocional han sembrado una semilla que no morirá."),
("Q-ENT-M36-EMO-014","M","Creo que nuestra familia es emocionalmente perfecta y un modelo absoluto para todas las familias.",True),
("Q-ENT-M36-EMO-015","E","Me pregunto cómo la plenitud emocional que vivimos puede ser un servicio para el mundo."),
("Q-ENT-M36-EMO-016","C","Logro vivir desde el amor pleno incluso con quienes en el pasado me generaron dolor o conflicto."),
("Q-ENT-M36-EMO-017","A","Noto que la capacidad de perdonar, agradecer y amar sin condición es ya parte de quiénes somos."),
("Q-ENT-M36-EMO-018","F","Percibo que la plenitud emocional de nuestra familia es un testimonio viviente de transformación."),
("Q-ENT-M36-EMO-019","A","Me doy cuenta de que el amor que cultivamos durante tres años es ahora un bien para la humanidad."),
("Q-ENT-M36-EMO-020","F","Acepto que la plenitud emocional requiere que continúe el camino aunque M36 sea un cierre y apertura."),
("Q-ENT-M36-EMO-021","C","Puedo mirar atrás tres años y ver con gratitud y asombro la transformación emocional vivida."),
("Q-ENT-M36-EMO-022","A","Noto que la familia está lista para iniciar un nuevo ciclo de transformación desde la plenitud."),
("Q-ENT-M36-EMO-023","F","Identifico que la plenitud emocional de M36 no es un final sino el inicio de una vida plena."),
("Q-ENT-M36-EMO-024","E","Me pregunto qué legado emocional vivirá en mis descendientes cuando ya no esté presente en este mundo."),
# ═══ M36 COMUNICACION (24) ═══
("Q-ENT-M36-COM-001","C","La comunicación en nuestra familia es ahora una expresión pura de amor, verdad y presencia plena."),
("Q-ENT-M36-COM-002","A","Noto que tres años de comunicación consciente han cambiado quiénes somos como personas y familia."),
("Q-ENT-M36-COM-003","F","Nuestra forma de comunicarnos es ya un legado vivo que trasciende nuestra generación."),
("Q-ENT-M36-COM-004","M","La comunicación de nuestra familia es perfecta y ya no necesita ninguna atención o trabajo.",True),
("Q-ENT-M36-COM-005","E","Observo de qué manera la calidad de nuestra comunicación puede seguir expandiéndose más allá de M36."),
("Q-ENT-M36-COM-006","C","Sostengo conversaciones de plenitud donde compartimos gratitud, propósito y visión del futuro."),
("Q-ENT-M36-COM-007","A","Noto que las palabras que usamos en familia ya son portadoras del amor y la transformación vivida."),
("Q-ENT-M36-COM-008","F","He alcanzado la plenitud comunicativa donde cada palabra nace del amor y no del ego ni del miedo."),
("Q-ENT-M36-COM-009","A","Me doy cuenta de que la comunicación de tres años de proceso ya vive en todos los que nos han visto."),
("Q-ENT-M36-COM-010","F","Acepto que la plenitud comunicativa es el estado desde el cual la familia puede servir al mundo."),
("Q-ENT-M36-COM-011","C","Identifico que nuestra familia puede comunicar amor de formas que trascienden el tiempo y el espacio."),
("Q-ENT-M36-COM-012","A","Noto que las generaciones jóvenes de nuestra familia ya se comunican desde la madurez y el amor."),
("Q-ENT-M36-COM-013","F","Reconozco que tres años de comunicación íntegra han construido una herencia de relaciones profundas."),
("Q-ENT-M36-COM-014","M","Creo que la comunicación de nuestra familia es un modelo perfecto e inmutable para siempre.",True),
("Q-ENT-M36-COM-015","E","Me pregunto cómo nuestra manera de comunicarnos puede inspirar a la siguiente generación de familias."),
("Q-ENT-M36-COM-016","C","Logro comunicar el amor pleno de una manera que sana, une y eleva a quienes lo reciben."),
("Q-ENT-M36-COM-017","A","Noto que la familia puede hablar de la muerte, el legado y el sentido de la vida con paz y apertura."),
("Q-ENT-M36-COM-018","F","Percibo que la comunicación de nuestra familia en M36 es una oración de amor hecha vida."),
("Q-ENT-M36-COM-019","A","Me doy cuenta de que comunicarnos con amor pleno es ya nuestra forma de ser y no un esfuerzo."),
("Q-ENT-M36-COM-020","F","Acepto que la plenitud comunicativa es el mayor servicio que puedo ofrecer a mi familia y al mundo."),
("Q-ENT-M36-COM-021","C","Puedo cerrar este ciclo de tres años con gratitud por cada conversación que construyó amor."),
("Q-ENT-M36-COM-022","A","Noto que la familia está lista para comenzar un nuevo ciclo comunicativo desde la plenitud ganada."),
("Q-ENT-M36-COM-023","F","Identifico que la comunicación plena de M36 es la semilla de los próximos tres años de crecimiento."),
("Q-ENT-M36-COM-024","E","Me pregunto qué conversación final de cierre y apertura quiero tener con mi familia al llegar a M36."),
# ═══ M36 HABITOS (24) ═══
("Q-ENT-M36-HAB-001","C","Los hábitos de nuestra familia en M36 son la expresión más pura de quiénes hemos elegido ser."),
("Q-ENT-M36-HAB-002","A","Noto que tres años de hábitos conscientes han transformado irreversiblemente la cultura de la familia."),
("Q-ENT-M36-HAB-003","F","He alcanzado la plenitud en los hábitos donde cada acción cotidiana es una expresión de amor."),
("Q-ENT-M36-HAB-004","M","Todos mis hábitos son perfectos y ya no necesito ningún tipo de revisión ni crecimiento adicional.",True),
("Q-ENT-M36-HAB-005","E","Observo qué hábitos nuevos quiero cultivar en el próximo ciclo que comienza después de M36."),
("Q-ENT-M36-HAB-006","C","Sostengo hábitos de plenitud que surgen de la convicción interior y no de la obligación externa."),
("Q-ENT-M36-HAB-007","A","Noto que los hábitos de servicio, generosidad y presencia son ya mi forma natural de vivir."),
("Q-ENT-M36-HAB-008","F","He integrado hábitos de plenitud que me conectan con el propósito más profundo de mi existencia."),
("Q-ENT-M36-HAB-009","A","Me doy cuenta de que los hábitos de tres años han creado una persona diferente a la que comenzó."),
("Q-ENT-M36-HAB-010","F","Acepto que los hábitos de plenitud requieren que siga creciendo más allá del fin del proceso."),
("Q-ENT-M36-HAB-011","C","Identifico que los hábitos que cultivamos son el patrimonio más valioso que dejamos como familia."),
("Q-ENT-M36-HAB-012","A","Noto que los hábitos plenos de M36 son la semilla de la siguiente generación de transformación."),
("Q-ENT-M36-HAB-013","F","Reconozco que tres años de hábitos conscientes nos han llevado a vivir desde la plenitud y el amor."),
("Q-ENT-M36-HAB-014","M","Considero que mis hábitos de plenitud son perfectos e inmejorables en todos los aspectos.",True),
("Q-ENT-M36-HAB-015","E","Me pregunto qué hábitos de plenitud quiero que mis hijos transmitan a sus propios hijos."),
("Q-ENT-M36-HAB-016","C","Logro vivir cada hábito cotidiano como una oración de amor y entrega a la vida y a los míos."),
("Q-ENT-M36-HAB-017","A","Noto que los hábitos de la plenitud no se imponen sino que fluyen desde lo que genuinamente soy."),
("Q-ENT-M36-HAB-018","F","Percibo que los hábitos de M36 son la culminación de un proceso que nunca realmente termina."),
("Q-ENT-M36-HAB-019","A","Me doy cuenta de que cada hábito pleno es un testimonio viviente de la transformación familiar."),
("Q-ENT-M36-HAB-020","F","Acepto que la plenitud en los hábitos es el punto de partida para el siguiente ciclo de crecimiento."),
("Q-ENT-M36-HAB-021","C","Puedo cerrar este ciclo de tres años de hábitos con orgullo, gratitud y apertura hacia lo que sigue."),
("Q-ENT-M36-HAB-022","A","Noto que la familia celebra los hábitos alcanzados en M36 como un logro colectivo y sagrado."),
("Q-ENT-M36-HAB-023","F","Identifico que los hábitos de plenitud de M36 son la base del próximo ciclo de trascendencia."),
("Q-ENT-M36-HAB-024","E","Me pregunto qué hábito, si lo comenzara hoy, transformaría el siguiente ciclo de nuestra familia."),
# ═══ M36 TIEMPOS (23) ═══
("Q-ENT-M36-TIE-001","C","El tiempo en M36 es vivido desde la plenitud: cada momento es sagrado, suficiente y eterno."),
("Q-ENT-M36-TIE-002","A","Noto que la forma en que vivo el tiempo familiar ha cambiado completamente en tres años de proceso."),
("Q-ENT-M36-TIE-003","F","Percibo que el tiempo pleno que vivimos es ya un testimonio de transformación para las generaciones."),
("Q-ENT-M36-TIE-004","M","Siempre vivo el tiempo con perfecta plenitud y no existen momentos que no sean sagrados.",True),
("Q-ENT-M36-TIE-005","E","Observo con gratitud cada momento familiar como parte del mosaico del legado que hemos construido."),
("Q-ENT-M36-TIE-006","C","Sostengo la presencia plena en el tiempo familiar porque es la forma más pura de amar que conozco."),
("Q-ENT-M36-TIE-007","A","Noto que el tiempo ya no es una carrera sino un río en el que me muevo con paz y propósito."),
("Q-ENT-M36-TIE-008","F","He llegado a un lugar donde el tiempo es vivido como plenitud y no como escasez ni urgencia."),
("Q-ENT-M36-TIE-009","A","Me doy cuenta de que cada momento con mi familia en M36 es la culminación de tres años de siembra."),
("Q-ENT-M36-TIE-010","F","Acepto que el tiempo pleno familiar es la herencia más pura e inmaterial que puedo dejar."),
("Q-ENT-M36-TIE-011","C","Identifico que el tiempo vivido con plena consciencia en familia trasciende el tiempo cronológico."),
("Q-ENT-M36-TIE-012","A","Noto que la familia en M36 vive los momentos compartidos con un nivel de presencia antes desconocido."),
("Q-ENT-M36-TIE-013","F","Reconozco que tres años de tiempo intencional han creado una historia familiar que no morirá."),
("Q-ENT-M36-TIE-014","M","En nuestra familia todos vivimos el tiempo con perfecta plenitud sin ningún espacio de mejora.",True),
("Q-ENT-M36-TIE-015","E","Me pregunto qué tipo de tiempo quiero seguir cultivando en el próximo ciclo más allá de M36."),
("Q-ENT-M36-TIE-016","C","Logro vivir el tiempo familiar en M36 como una oración de gratitud y amor hacia la vida."),
("Q-ENT-M36-TIE-017","A","Noto que la familia valora cada momento compartido como el regalo más preciado de la existencia."),
("Q-ENT-M36-TIE-018","F","Percibo que el tiempo pleno de M36 es el inicio de una forma nueva de vivir que comienza ahora."),
("Q-ENT-M36-TIE-019","A","Me doy cuenta de que llegar a M36 con plenitud en el tiempo es un logro que merece celebración."),
("Q-ENT-M36-TIE-020","F","Acepto que el tiempo de plenitud en M36 no es el final sino la apertura de una nueva etapa."),
("Q-ENT-M36-TIE-021","C","Puedo mirar los tres años de tiempo familiar invertido y ver con claridad el legado que sembramos."),
("Q-ENT-M36-TIE-022","A","Noto que la familia está lista para iniciar un nuevo ciclo desde el tiempo de la plenitud ganada."),
("Q-ENT-M36-TIE-023","E","Me pregunto qué recordarán mis descendientes sobre cómo viví el tiempo con amor en esta familia."),
]

out_path=os.path.join(os.path.dirname(__file__),"questions_part4.json")
data={"version":"2.0-part4","count":len(R),"questions":build(R)}
with open(out_path,"w",encoding="utf-8") as f:
    json.dump(data,f,ensure_ascii=False,indent=2)
print(f"OK Generadas {len(R)} preguntas -> {out_path}")
