#!/usr/bin/env python3
"""Genera questions_part2.json — M3 + M6 (210 preguntas)"""
import json, os, sys
sys.path.insert(0,os.path.dirname(__file__))
from gen_questions_p1 import meta, TT, build

R=[
# ═══ M3 EMOCIONES (25) — Cimentacion de Vinculos ═══
("Q-REC-M3-EMO-001","C","He comenzado a gestionar mis emociones difíciles de forma más consciente y eficaz."),
("Q-REC-M3-EMO-002","A","Noto que la convivencia familiar se siente más estable emocionalmente que hace tres meses."),
("Q-REC-M3-EMO-003","F","Percibo que los vínculos familiares se están cimentando sobre bases emocionales más sólidas."),
("Q-REC-M3-EMO-004","M","Nunca tengo momentos de regresión emocional y siempre mantengo la calma perfecta.",True),
("Q-REC-M3-EMO-005","E","Observo si existen emociones de meses anteriores que aún no hemos procesado juntos."),
("Q-REC-M3-EMO-006","C","Logro hacer una pausa real antes de reaccionar en momentos de tensión familiar."),
("Q-REC-M3-EMO-007","A","Noto que mis respuestas emocionales son más proporcionales a las situaciones actuales."),
("Q-REC-M3-EMO-008","F","Reconozco la importancia de reparar emocionalmente después de un conflicto familiar."),
("Q-REC-M3-EMO-009","A","Me doy cuenta de que la regulación emocional mejora pero aún requiere esfuerzo consciente."),
("Q-REC-M3-EMO-010","F","Acepto que el crecimiento emocional implica avances, retrocesos y nuevos avances naturales."),
("Q-REC-M3-EMO-011","C","Identifico que la resiliencia emocional familiar está creciendo gradualmente en nosotros."),
("Q-REC-M3-EMO-012","A","Noto si el clima emocional del hogar está más cargado de lo que reconocemos verbalmente."),
("Q-REC-M3-EMO-013","F","Percibo que mis hijos o familiares sienten una mayor seguridad emocional en el hogar."),
("Q-REC-M3-EMO-014","M","Creo que nuestra familia ya alcanzó la estabilidad emocional total y no necesita más trabajo.",True),
("Q-REC-M3-EMO-015","E","Me pregunto cómo sería nuestra familia si cada miembro trabajara sus emociones profundas."),
("Q-REC-M3-EMO-016","C","He aprendido a identificar mis necesidades emocionales antes de que escalen a conflicto."),
("Q-REC-M3-EMO-017","A","Noto que el miedo al conflicto ya no me impide abordar temas emocionales importantes."),
("Q-REC-M3-EMO-018","F","Reconozco que expresar vulnerabilidad es un acto de fortaleza y no de debilidad."),
("Q-REC-M3-EMO-019","A","Me doy cuenta de que hay miembros familiares que aún no han iniciado su proceso emocional."),
("Q-REC-M3-EMO-020","F","Acepto que cada persona avanza a su propio ritmo en el proceso de conciencia emocional."),
("Q-REC-M3-EMO-021","C","Percibo la diferencia entre contener emocionalmente a alguien y sobreprotegerlo."),
("Q-REC-M3-EMO-022","A","Noto si estoy comenzando a crear espacios seguros donde los demás pueden expresarse."),
("Q-REC-M3-EMO-023","F","Identifico qué emociones específicas siguen siendo difíciles de gestionar conscientemente."),
("Q-REC-M3-EMO-024","A","Me doy cuenta de que el amor emocional requiere también límites sanos y claros."),
("Q-REC-M3-EMO-025","E","Observo si el proceso de transformación emocional ha comenzado a ser percibido por otros."),
# ═══ M3 COMUNICACION (25) ═══
("Q-REC-M3-COM-001","C","Las conversaciones difíciles en casa ya no terminan siempre en distancia o silencio."),
("Q-REC-M3-COM-002","A","Noto que la calidad de la escucha en nuestra familia ha mejorado significativamente."),
("Q-REC-M3-COM-003","F","Percibo que empezamos a construir conversaciones basadas en el respeto y la apertura."),
("Q-REC-M3-COM-004","M","En nuestra familia ya nos comunicamos perfectamente y no necesitamos más ajustes.",True),
("Q-REC-M3-COM-005","E","Me pregunto qué tipo de conversaciones transformadoras aún no nos atrevemos a tener."),
("Q-REC-M3-COM-006","C","Puedo expresar mis necesidades con más claridad sin necesidad de reclamar o herir."),
("Q-REC-M3-COM-007","A","Noto que ya no necesito gritar o callarme para sentir que me escuchan en casa."),
("Q-REC-M3-COM-008","F","Reconozco que hay temas que hemos comenzado a abordar que antes estaban completamente prohibidos."),
("Q-REC-M3-COM-009","A","Me doy cuenta de que nuestra familia empieza a construir acuerdos conversacionales nuevos."),
("Q-REC-M3-COM-010","F","Acepto que hay conversaciones pendientes que requieren valentía y el momento apropiado."),
("Q-REC-M3-COM-011","C","Identifico si nuestra forma de comunicarnos está creando vínculos o barreras invisibles."),
("Q-REC-M3-COM-012","A","Noto que la comunicación en momentos de desacuerdo es más respetuosa que antes."),
("Q-REC-M3-COM-013","F","Percibo que la familia empieza a verbalizar más el afecto y el reconocimiento mutuo."),
("Q-REC-M3-COM-014","M","Considero que ya nunca lastimamos a nadie con palabras y comunicamos todo perfectamente.",True),
("Q-REC-M3-COM-015","E","Observo si los silencios en casa comunican paz o aún comunican distancia y evitación."),
("Q-REC-M3-COM-016","C","Reconozco que comunicarme bien con mi familia requiere intención activa y práctica diaria."),
("Q-REC-M3-COM-017","A","Noto si las conversaciones que antes terminaban en pleito ahora tienen un final diferente."),
("Q-REC-M3-COM-018","F","Identifico el progreso en comunicación como evidencia concreta del proceso de transformación."),
("Q-REC-M3-COM-019","A","Me doy cuenta de que empiezo a usar palabras que unen y que generan seguridad en los demás."),
("Q-REC-M3-COM-020","F","Acepto que aprender a comunicarse sanamente es una de las tareas más importantes en familia."),
("Q-REC-M3-COM-021","C","Percibo si la comunicación familiar en su conjunto es más abierta que hace tres meses."),
("Q-REC-M3-COM-022","A","Noto si los jóvenes o hijos se comunican ahora con más confianza que antes."),
("Q-REC-M3-COM-023","F","Reconozco los avances concretos en comunicación aunque aún quede camino por recorrer."),
("Q-REC-M3-COM-024","A","Me doy cuenta de que validar las emociones de los demás mejora profundamente la comunicación."),
("Q-REC-M3-COM-025","E","Me pregunto qué tipo de escucha profunda necesita cada miembro específico de mi familia."),
# ═══ M3 HABITOS (25) ═══
("Q-REC-M3-HAB-001","C","He establecido al menos tres hábitos nuevos que favorecen la convivencia familiar."),
("Q-REC-M3-HAB-002","A","Noto que los rituales familiares pequeños empiezan a tener constancia y regularidad."),
("Q-REC-M3-HAB-003","F","Percibo que los hábitos que construimos están cimentando los vínculos entre nosotros."),
("Q-REC-M3-HAB-004","M","Todos los miembros de mi familia han adoptado perfectamente todos los hábitos propuestos.",True),
("Q-REC-M3-HAB-005","E","Observo cuáles de los nuevos hábitos generan mayor bienestar e impacto en la familia."),
("Q-REC-M3-HAB-006","C","Identifico que la constancia en los hábitos ya está generando cambios visibles en casa."),
("Q-REC-M3-HAB-007","A","Noto que el uso de pantallas y tecnología está siendo más regulado en el hogar."),
("Q-REC-M3-HAB-008","F","Reconozco que los hábitos de salud emocional son tan importantes como los hábitos físicos."),
("Q-REC-M3-HAB-009","A","Me doy cuenta de que los acuerdos familiares se cumplen con mayor regularidad ahora."),
("Q-REC-M3-HAB-010","F","Acepto que consolidar un hábito requiere al menos tres meses de práctica sostenida."),
("Q-REC-M3-HAB-011","C","Puedo nombrar hábitos concretos que antes no existían y que ahora ya son parte de nosotros."),
("Q-REC-M3-HAB-012","A","Noto que los hábitos de convivencia que practicamos los hijos están comenzando a imitar."),
("Q-REC-M3-HAB-013","F","Percibo que el hábito de la pausa reflexiva antes de responder se está instalando."),
("Q-REC-M3-HAB-014","M","Nuestra familia nunca tiene problemas con la consistencia de hábitos y compromisos.",True),
("Q-REC-M3-HAB-015","E","Me pregunto cuáles hábitos necesitamos afianzar más para sostener el proceso completo."),
("Q-REC-M3-HAB-016","C","Reconozco que los hábitos familiares saludables son el cimiento de la transformación."),
("Q-REC-M3-HAB-017","A","Noto que el ritual de la cena o comida compartida se está recuperando gradualmente."),
("Q-REC-M3-HAB-018","F","Identifico que el hábito de gratitud explícita empieza a aparecer con más frecuencia."),
("Q-REC-M3-HAB-019","A","Me doy cuenta de que algunos hábitos viejos reaparecen bajo el estrés pero los reconozco."),
("Q-REC-M3-HAB-020","F","Acepto que mantener los hábitos en épocas difíciles es el verdadero indicador de cambio."),
("Q-REC-M3-HAB-021","C","Observo si los hábitos que construimos reflejan los valores que queremos vivir como familia."),
("Q-REC-M3-HAB-022","A","Noto si hay resistencia de algún miembro para adoptar los hábitos familiares acordados."),
("Q-REC-M3-HAB-023","F","Reconozco que cada hábito sostenido por tres meses es una victoria del proceso familiar."),
("Q-REC-M3-HAB-024","A","Me doy cuenta de que mi consistencia personal en los hábitos inspira a los demás."),
("Q-REC-M3-HAB-025","E","Me pregunto qué hábito compartido transformaría más rápido la dinámica de nuestra familia."),
# ═══ M3 TIEMPOS (25) ═══
("Q-REC-M3-TIE-001","C","Tengo rituales de tiempo familiar establecidos que se respetan de forma consistente."),
("Q-REC-M3-TIE-002","A","Noto que el balance entre tiempo personal y tiempo familiar ha mejorado en tres meses."),
("Q-REC-M3-TIE-003","F","Percibo que los momentos de tiempo compartido están construyendo vínculos más sólidos."),
("Q-REC-M3-TIE-004","M","En nuestra familia el tiempo siempre se distribuye perfectamente y todos están satisfechos.",True),
("Q-REC-M3-TIE-005","E","Observo qué actividades familiares compartidas generan mayor conexión e historia común."),
("Q-REC-M3-TIE-006","C","Identifico que el tiempo sin pantallas en familia se ha vuelto más natural y frecuente."),
("Q-REC-M3-TIE-007","A","Noto que las interrupciones tecnológicas durante el tiempo familiar han disminuido."),
("Q-REC-M3-TIE-008","F","Reconozco que crear tradiciones familiares requiere tiempo, intención y constancia."),
("Q-REC-M3-TIE-009","A","Me doy cuenta de que el tiempo de calidad con cada miembro fortalece vínculos únicos."),
("Q-REC-M3-TIE-010","F","Acepto que el tiempo es el recurso más valioso que puedo ofrecer a mi familia."),
("Q-REC-M3-TIE-011","C","Puedo identificar al menos tres momentos semanales de conexión familiar real y consciente."),
("Q-REC-M3-TIE-012","A","Noto que los fines de semana empiezan a incluir actividades de conexión familiar planificadas."),
("Q-REC-M3-TIE-013","F","Percibo que la familia tiene más momentos de alegría compartida que hace tres meses."),
("Q-REC-M3-TIE-014","M","Nunca falta tiempo en nuestra familia y todos siempre se sienten plenamente atendidos.",True),
("Q-REC-M3-TIE-015","E","Me pregunto cómo nuestros hijos recordarán el tiempo que pasamos juntos en esta etapa."),
("Q-REC-M3-TIE-016","C","Reconozco que el tiempo familiar no puede posponerse indefinidamente sin consecuencias."),
("Q-REC-M3-TIE-017","A","Noto si el tiempo de pareja dentro de la familia también está siendo nutrido y cuidado."),
("Q-REC-M3-TIE-018","F","Identifico que los rituales de tiempo familiar dan seguridad y pertenencia a todos."),
("Q-REC-M3-TIE-019","A","Me doy cuenta de que el tiempo consciente con los hijos es una inversión en su futuro."),
("Q-REC-M3-TIE-020","F","Acepto que la familia necesita tiempo de conexión tan urgentemente como cualquier otro compromiso."),
("Q-REC-M3-TIE-021","C","Observo si los espacios de tiempo familiar ya están siendo protegidos de otras demandas."),
("Q-REC-M3-TIE-022","A","Noto que llego a los momentos familiares con más presencia y menos preocupación laboral."),
("Q-REC-M3-TIE-023","F","Reconozco que los momentos de tiempo familiar acumulados construyen la historia familiar."),
("Q-REC-M3-TIE-024","A","Me doy cuenta de que el tiempo de calidad no necesita ser costoso ni sobreplanificado."),
("Q-REC-M3-TIE-025","E","Me pregunto qué recuerdos estamos creando ahora que nuestra familia atesorará siempre."),
# ═══ M6 EMOCIONES (28) — Transformacion Profunda ═══
("Q-AMO-M6-EMO-001","C","Puedo regularme emocionalmente incluso en medio de conflictos familiares intensos."),
("Q-AMO-M6-EMO-002","A","Noto que mi familia empieza a percibir estabilidad emocional en mí con más frecuencia."),
("Q-AMO-M6-EMO-003","F","He aprendido a reparar la relación después de haberme equivocado o reaccionado mal."),
("Q-AMO-M6-EMO-004","M","En nuestra familia nunca existen recaídas emocionales y todo avanza de forma perfectamente lineal.",True),
("Q-AMO-M6-EMO-005","E","Me pregunto qué emociones específicas aún generan regresión o conflicto en mi familia."),
("Q-AMO-M6-EMO-006","C","Elijo conscientemente cómo responder en lugar de reaccionar automáticamente en casa."),
("Q-AMO-M6-EMO-007","A","Noto que cuando me desregulo emocionalmente puedo recuperarme más rápido que antes."),
("Q-AMO-M6-EMO-008","F","Percibo que la compasión hacia mí mismo y hacia los demás ha crecido profundamente."),
("Q-AMO-M6-EMO-009","A","Me doy cuenta de que puedo contener emocionalmente a mi familia sin perderme a mí mismo."),
("Q-AMO-M6-EMO-010","F","Acepto que la transformación emocional profunda requiere tiempo y permite el error natural."),
("Q-AMO-M6-EMO-011","C","Identifico que el amor como elección consciente es más estable que el amor reactivo."),
("Q-AMO-M6-EMO-012","A","Noto si hay patrones emocionales que se activan particularmente en ciertos miembros."),
("Q-AMO-M6-EMO-013","F","Reconozco que puedo estar presente en el dolor de otro sin necesitar resolverlo."),
("Q-AMO-M6-EMO-014","M","Considero que ya soy emocionalmente perfecto y no necesito ningún trabajo adicional.",True),
("Q-AMO-M6-EMO-015","E","Observo cuáles experiencias emocionales han marcado más profundamente a mi familia."),
("Q-AMO-M6-EMO-016","C","He desarrollado la capacidad de regular mis emociones antes de que afecten el hogar."),
("Q-AMO-M6-EMO-017","A","Noto que el enojo ya no es mi respuesta automática cuando algo sale mal en casa."),
("Q-AMO-M6-EMO-018","F","Percibo que la familia siente más seguridad emocional gracias a mi mayor estabilidad."),
("Q-AMO-M6-EMO-019","A","Me doy cuenta de que mi capacidad de pedir perdón genuinamente ha aumentado mucho."),
("Q-AMO-M6-EMO-020","F","Acepto que ser emocionalmente maduro no significa no sentir sino elegir cómo actuar."),
("Q-AMO-M6-EMO-021","C","Logro sostener la calma cuando alguien en casa atraviesa una crisis emocional intensa."),
("Q-AMO-M6-EMO-022","A","Noto que los momentos de conexión emocional profunda son más frecuentes que antes."),
("Q-AMO-M6-EMO-023","F","Identifico que la gratitud se ha convertido en un estado más frecuente en mi vida familiar."),
("Q-AMO-M6-EMO-024","A","Me doy cuenta de que empiezo a ver los conflictos como oportunidades de crecimiento."),
("Q-AMO-M6-EMO-025","F","Reconozco que la herida emocional no reparada tiene un costo real y concreto en la familia."),
("Q-AMO-M6-EMO-026","C","Percibo que la transformación emocional en mí está generando transformación en los demás."),
("Q-AMO-M6-EMO-027","A","Noto si hay miembros que todavía no pueden regular sus emociones y necesitan apoyo."),
("Q-AMO-M6-EMO-028","E","Me pregunto cómo sería nuestra familia si todos practicáramos la regulación emocional consciente."),
# ═══ M6 COMUNICACION (28) ═══
("Q-AMO-M6-COM-001","C","Los conflictos en casa terminan en entendimiento y no en distancia o silencio prolongado."),
("Q-AMO-M6-COM-002","A","Noto que puedo expresar mis necesidades profundas sin herir ni manipular a los demás."),
("Q-AMO-M6-COM-003","F","Nuestra familia ya conversa temas difíciles sin que la relación se rompa o dañe."),
("Q-AMO-M6-COM-004","M","En nuestra familia todos nos comunicamos siempre con perfección y nunca hay fricciones.",True),
("Q-AMO-M6-COM-005","E","Me pregunto qué conversación profunda podría transformar más nuestra dinámica familiar."),
("Q-AMO-M6-COM-006","C","Puedo decir la verdad con amor incluso cuando sé que no es lo que quieren escuchar."),
("Q-AMO-M6-COM-007","A","Noto que el tono de las conversaciones en casa es más cálido y respetuoso que antes."),
("Q-AMO-M6-COM-008","F","He desarrollado la habilidad de escuchar sin juzgar aunque no comparta el punto de vista."),
("Q-AMO-M6-COM-009","A","Me doy cuenta de que ya no huyo de las conversaciones difíciles por miedo o incomodidad."),
("Q-AMO-M6-COM-010","F","Acepto que la comunicación honesta y amorosa es la base de una familia transformada."),
("Q-AMO-M6-COM-011","C","Identifico que nuestras conversaciones ahora tienen más profundidad y menos superficialidad."),
("Q-AMO-M6-COM-012","A","Noto que los jóvenes o hijos ya buscan hablar conmigo sobre lo que realmente les preocupa."),
("Q-AMO-M6-COM-013","F","Reconozco que hablar de las necesidades emocionales sin vergüenza fortalece los vínculos."),
("Q-AMO-M6-COM-014","M","Considero que ya no existe ningún tema difícil de comunicar en nuestra familia.",True),
("Q-AMO-M6-COM-015","E","Observo si la calidad de la comunicación refleja el nivel de transformación alcanzado."),
("Q-AMO-M6-COM-016","C","Puedo pedir disculpas genuinas y recibir críticas sin ponerme a la defensiva."),
("Q-AMO-M6-COM-017","A","Noto que los acuerdos familiares se construyen con diálogo real y no solo con imposición."),
("Q-AMO-M6-COM-018","F","Percibo que la familia habla más del futuro que deseamos que del pasado que nos duele."),
("Q-AMO-M6-COM-019","A","Me doy cuenta de que el humor y la ligereza también son formas de comunicación sana."),
("Q-AMO-M6-COM-020","F","Acepto que comunicar el amor de forma explícita y regular es una responsabilidad familiar."),
("Q-AMO-M6-COM-021","C","Logro mantener conversaciones difíciles sin perder la serenidad ni el respeto mutuo."),
("Q-AMO-M6-COM-022","A","Noto que mis palabras de aliento y reconocimiento son más frecuentes que las de crítica."),
("Q-AMO-M6-COM-023","F","Identifico que la calidad de la comunicación en M6 es evidencia del trabajo realizado."),
("Q-AMO-M6-COM-024","A","Me doy cuenta de que decir te quiero con actos diarios complementa las palabras."),
("Q-AMO-M6-COM-025","F","Reconozco que construir un lenguaje familiar positivo requiere práctica consciente constante."),
("Q-AMO-M6-COM-026","C","Percibo que nuestra familia tiene ahora un vocabulario emocional más amplio y honesto."),
("Q-AMO-M6-COM-027","A","Noto si hay conversaciones que tenemos frecuentemente que siguen sin llegar a resolución."),
("Q-AMO-M6-COM-028","E","Me pregunto cuál sería la conversación más transformadora que podríamos tener como familia."),
# ═══ M6 HABITOS (27) ═══
("Q-AMO-M6-HAB-001","C","Los hábitos de transformación iniciados hace seis meses ya son parte de nuestra identidad."),
("Q-AMO-M6-HAB-002","A","Noto que los rituales familiares que creamos son sostenidos incluso en épocas de estrés."),
("Q-AMO-M6-HAB-003","F","Percibo que nuestra familia ha desarrollado hábitos de conexión que antes no existían."),
("Q-AMO-M6-HAB-004","M","En nuestra familia todos los hábitos propuestos funcionan perfectamente sin ningún esfuerzo.",True),
("Q-AMO-M6-HAB-005","E","Observo qué nuevos hábitos podríamos incorporar en esta etapa de transformación profunda."),
("Q-AMO-M6-HAB-006","C","Identifico que los hábitos de regulación emocional se están integrando gradualmente."),
("Q-AMO-M6-HAB-007","A","Noto que el hábito de reconocer y celebrar los avances fortalece la motivación familiar."),
("Q-AMO-M6-HAB-008","F","Reconozco que los hábitos saludables ahora requieren menos esfuerzo consciente que antes."),
("Q-AMO-M6-HAB-009","A","Me doy cuenta de que los hábitos de escucha activa se practican más naturalmente."),
("Q-AMO-M6-HAB-010","F","Acepto que transformar hábitos profundos toma tiempo pero los resultados ya son visibles."),
("Q-AMO-M6-HAB-011","C","Puedo identificar hábitos de la etapa anterior que ya han sido consolidados exitosamente."),
("Q-AMO-M6-HAB-012","A","Noto que el hábito del agradecimiento mutuo es más frecuente en las interacciones familiares."),
("Q-AMO-M6-HAB-013","F","Percibo que los hábitos de presencia consciente están reemplazando los de distracción."),
("Q-AMO-M6-HAB-014","M","Considero que todos los hábitos están perfectamente integrados sin ninguna resistencia.",True),
("Q-AMO-M6-HAB-015","E","Me pregunto qué hábitos espirituales o de reflexión podríamos añadir al proceso familiar."),
("Q-AMO-M6-HAB-016","C","Reconozco que la constancia en los hábitos es la evidencia más real de la transformación."),
("Q-AMO-M6-HAB-017","A","Noto si hay hábitos que funcionan bien individualmente pero falta coordinarlos como familia."),
("Q-AMO-M6-HAB-018","F","Identifico que los hábitos de cuidado mutuo están comenzando a ser naturales y espontáneos."),
("Q-AMO-M6-HAB-019","A","Me doy cuenta de que los hábitos de convivencia sana se están transmitiendo a los hijos."),
("Q-AMO-M6-HAB-020","F","Acepto que algunos hábitos necesitan revisarse o ajustarse a medida que la familia crece."),
("Q-AMO-M6-HAB-021","C","Logro mantener los hábitos de transformación incluso cuando enfrentamos períodos de crisis."),
("Q-AMO-M6-HAB-022","A","Noto que el hábito de la reparación después del conflicto ya es parte de nuestra cultura."),
("Q-AMO-M6-HAB-023","F","Reconozco que los hábitos familiares que construimos son nuestra mayor inversión a largo plazo."),
("Q-AMO-M6-HAB-024","A","Me doy cuenta de que celebrar los pequeños logros habitúa a la familia a la gratitud.",False,True),
("Q-AMO-M6-HAB-025","E","Observo si hay hábitos que necesitamos reforzar antes de avanzar a la siguiente etapa."),
("Q-AMO-M6-HAB-026","A","Noto que el hábito del perdón genuino está reemplazando al del rencor o la distancia."),
("Q-AMO-M6-HAB-027","F","Identifico que en seis meses de proceso hemos construido una cultura familiar diferente."),
# ═══ M6 TIEMPOS (27) ═══
("Q-AMO-M6-TIE-001","C","El tiempo familiar es ahora una prioridad que protegemos activamente de otras demandas."),
("Q-AMO-M6-TIE-002","A","Noto que los momentos de conexión familiar son más profundos y menos superficiales que antes."),
("Q-AMO-M6-TIE-003","F","Percibo que el tiempo invertido en los primeros seis meses ya está generando frutos reales."),
("Q-AMO-M6-TIE-004","M","En nuestra familia el tiempo siempre se organiza perfectamente y nadie se siente descuidado.",True),
("Q-AMO-M6-TIE-005","E","Me pregunto qué tipo de experiencias compartidas quiero crear en la siguiente etapa."),
("Q-AMO-M6-TIE-006","C","Identifico que la calidad de mi presencia durante el tiempo familiar ha mejorado enormemente."),
("Q-AMO-M6-TIE-007","A","Noto que los rituales de tiempo compartido son ahora parte esencial de nuestra semana."),
("Q-AMO-M6-TIE-008","F","Reconozco que el tiempo sin pantallas ha generado conversaciones que antes no existían."),
("Q-AMO-M6-TIE-009","A","Me doy cuenta de que los viajes o actividades familiares construyen identidad y memoria común."),
("Q-AMO-M6-TIE-010","F","Acepto que el tiempo de pareja dentro de la familia también requiere cuidado y presencia."),
("Q-AMO-M6-TIE-011","C","Logro desconectarme del trabajo con mayor facilidad para estar realmente presente en casa."),
("Q-AMO-M6-TIE-012","A","Noto que los hijos buscan más tiempo conmigo cuando hay más presencia consciente de mi parte."),
("Q-AMO-M6-TIE-013","F","Percibo que la cantidad de tiempo que pasamos juntos está equilibrada con la calidad."),
("Q-AMO-M6-TIE-014","M","Siempre tenemos tiempo perfecto para todo y nunca falta nada en nuestra vida familiar.",True),
("Q-AMO-M6-TIE-015","E","Observo qué tipo de tiempo necesita cada miembro específico de mi familia de forma individual."),
("Q-AMO-M6-TIE-016","C","Reconozco que el tiempo de calidad con cada miembro es un acto de amor individualizado."),
("Q-AMO-M6-TIE-017","A","Noto que los momentos de tiempo familiar sin agenda generan conexión más profunda."),
("Q-AMO-M6-TIE-018","F","Identifico que el tiempo que damos en esta etapa sienta las bases del legado familiar."),
("Q-AMO-M6-TIE-019","A","Me doy cuenta de que la pausa del celular durante las comidas ha cambiado nuestra calidad."),
("Q-AMO-M6-TIE-020","F","Acepto que crear tradiciones familiares requiere tiempo intencional y consistente."),
("Q-AMO-M6-TIE-021","C","Percibo que el tiempo familiar invertido en seis meses ya tiene impacto visible en los hijos."),
("Q-AMO-M6-TIE-022","A","Noto si el tiempo de soledad personal me recarga para estar mejor presente en familia."),
("Q-AMO-M6-TIE-023","F","Reconozco que el tiempo compartido en amor es el legado más importante que puedo dejar."),
("Q-AMO-M6-TIE-024","A","Me doy cuenta de que la familia tiene ahora momentos propios que la identifican y unen."),
("Q-AMO-M6-TIE-025","E","Me pregunto cómo quiero que se vea nuestra familia en el tiempo cuando lleguemos a M12."),
("Q-AMO-M6-TIE-026","F","Identifico en el tiempo una herramienta de transformación que uso cada vez más conscientemente."),
("Q-AMO-M6-TIE-027","A","Noto que el tiempo de calidad con los abuelos u otras generaciones también merece cuidado."),
]

out_path=os.path.join(os.path.dirname(__file__),"questions_part2.json")
data={"version":"2.0-part2","count":len(R),"questions":build(R)}
with open(out_path,"w",encoding="utf-8") as f:
    json.dump(data,f,ensure_ascii=False,indent=2)
print(f"OK Generadas {len(R)} preguntas -> {out_path}")
